<?php

/**
 * BaseGeoIpRu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $start
 * @property integer $end
 * @property integer $region_id
 * @property string $region
 * @property string $city
 * 
 * @method integer getStart()     Returns the current record's "start" value
 * @method integer getEnd()       Returns the current record's "end" value
 * @method integer getRegionId()  Returns the current record's "region_id" value
 * @method string  getRegion()    Returns the current record's "region" value
 * @method string  getCity()      Returns the current record's "city" value
 * @method GeoIpRu setStart()     Sets the current record's "start" value
 * @method GeoIpRu setEnd()       Sets the current record's "end" value
 * @method GeoIpRu setRegionId()  Sets the current record's "region_id" value
 * @method GeoIpRu setRegion()    Sets the current record's "region" value
 * @method GeoIpRu setCity()      Sets the current record's "city" value
 * 
 * @package    domus
 * @subpackage model
 * @author     Garin Studio
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGeoIpRu extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('geo_ip_ru');
        $this->hasColumn('start', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('end', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('region_id', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => 1,
             'length' => 1,
             ));
        $this->hasColumn('region', 'string', 80, array(
             'type' => 'string',
             'length' => 80,
             ));
        $this->hasColumn('city', 'string', 60, array(
             'type' => 'string',
             'length' => 60,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}