default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css, backend.css, ie6.css, ie7.css, ie8.css]

  javascripts:    [jquery.js, backend.js]

  has_layout:     true
  layout:         layout
