generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Post
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          qa
    with_doctrine_route:     1

    config:
      actions:
        _edit: { credentials: [redactor-qa-actions] }
        _delete: { credentials: [redactor-qa-delete] }
      fields:
        themes_list: { label: Тема вопроса }
        author_name: { label: Имя автора }
      list:
        fields:
          author_and_user: { label: Пользователь }
          title_and_query: { label: Заголовок и Вопрос }
          themes_list: { label: Тема вопроса }
          author_name: { label: Имя автора }
        display: [_author_and_user, _title_and_query]
        sort: [created_at, desc]
        title: Вопрос & Ответ
        max_per_page: 10
      filter:
        class: QAFormFilter
      form:
        class: QAForm
      edit:
        title: Редактирование вопроса "%%title%%" от %%created_at%%
      new:
        title: Добавление вопроса
