<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Agency extends BaseAgency
{
  public function getDescriptionShort()
  {
    $lines = explode("\n", $this->description);
    return $lines[0];
  }

  public function getLogo()
  {
    $path = $this->getLogoPath(false);
    $pattern = sprintf('%s/%s/logo.*', sfConfig::get('sf_web_dir'), $path);
    foreach (glob($pattern) as $file) {
      return sprintf('/%s/%s', $path, basename($file));
    }
  }

  public function getLogoPath($create = true)
  {
    return Toolkit::buildStoragePath('agency', $this->id, true, $create);
  }
}