<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BlogTable extends Doctrine_Table
{
  public function getActiveBlogs() {
    return $this->createQuery('b')
      ->leftJoin('b.BlogPost p')
      ->where('b.status = ?', 'active')
      ->addHaving('count(p.id) > ?', 0)
      ->groupBy('b.id')
      ->execute();
  }

  public function getActiveBlog($url) {
    return $this->createQuery()
      ->where('status = ?', 'active')
      ->andWhere('url = ?', $url)
      ->fetchOne();

  }
}