<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BlogPost extends BaseBlogPost
{
  public static $status = array(
    'publish' => 'опубликовано',
    'not_publish' => 'не опубликовано',
    'restricted' => 'заблокировано',
    'moderate' => 'на модерации'
  );

  public function getUser()
  {
    return $this->Blog->User;
  }

}