<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BlogPostTable extends Doctrine_Table
{
  public function getActiveBlogPostsQuery($id) {
    return $this->createQuery()
      ->where('blog_id = ?', $id)
      ->andWhere('status = ?', 'publish')
      ->orderBy('created_at DESC');
  }
}