<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Claim extends BaseClaim
{
  public static $status = array(
    '' => 'все жалобы',
    'new' => 'новая',
//    'confirmed' => 'подтверждено',
//    'not_confirmed' => 'не подтверждено',
//    'on_control' => 'на контроле',
//    'need_check' => 'необходимо проверить',
    'fixed' => 'рассмотрена'
  );
}