<?php

/**
 * FormItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    domus
 * @subpackage model
 * @author     Garin Studio
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class FormItem extends BaseFormItem
{
}
