<?php

/**
 * FormItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FormItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FormItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FormItem');
    }
}