<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ImportOrder extends BaseImportOrder
{
  public static
    $_statuses = array(
      'inactive'  =>  'неоплачен',
      'active'    =>  'оплачен',
    );

  public function save(Doctrine_Connection $conn = null)
  {
    $modified = $this->getModified();
    if (!empty($modified['status'])) {
      if ($modified['status'] == 'active') {
        $this->date_from  = date('Y-m-d H:i:s');
        $this->date_to    = date("Y-m-d H:i:s",  strtotime("+1 month", strtotime($this->date_from)));
      }
    }
    parent::save($conn);
    return $this->id;
  }
}