<?php

/**
 * LandingPageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LandingPageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LandingPageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LandingPage');
    }
}