<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LotInfo extends BaseLotInfo
{
  public function setValue($value)
  {
    if (is_array($value)) {
      $value = implode(', ', $value);
    }
    elseif (is_numeric($value)) {
      $value = (string) trim($value);
      if (preg_match('/^[0-9]+(\.|,)[0-9]+$/', $value)) {
        $value = preg_replace('/[^0-9.,]/', '', $value);
      }
      else {
        $value = (int) $value;
      }
      $value = substr($value, 0, 12);
    }
    elseif (is_bool($value)) {
      if (!$value) {
        return null;
      }
      $value = $value ? '1' : '0';
    }

    return $this->_set('value', strip_tags($value));
  }

}