<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModeratorFiltersTable extends Doctrine_Table
{
  public function getFiltersForUser($user_id) {
    return $this->createQuery()
      ->select('id, name')
      ->where('user_id = ?', $user_id)
      ->orderBy('name')
      ->execute();
  }
}