<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PageTable extends Doctrine_Table
{
  public function createQuery($alias = '') {
    return parent::createQuery($alias)->orderBy('position');
  }

  public function normalize()
  {
    $pages = $this->createQuery()->execute();
    foreach ($pages as $page) {
      $page->position = empty($i) ? $i = 1 : ++$i;
      $page->save();
    }
  }

  public function checkAndNormalize()
  {
    $query = $this->createQuery()
      ->groupBy('position')
      ->having('count(*) > 1');

    if ($query->count()) {
      $this->normalize();
    }
  }
}