<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PMTable extends Doctrine_Table
{
  public function createQueryReceived($user_id)
  {
    return $this->createQuery()
      ->where('receiver = ?', $user_id)
      ->andWhere('is_deleted is null or not(is_deleted & ?)', PM::DELETED_RECEIVER)
      ->leftJoin('PM.UserSender')
      ->orderBy('red, sent_at desc');
  }

  public function createQuerySent($user_id)
  {
    return $this->createQuery()
      ->where('sender = ?', $user_id)
      ->andWhere('is_deleted is null or not(is_deleted & ?)', PM::DELETED_SENDER)
      ->leftJoin('PM.UserReceiver')
      ->orderBy('sent_at desc');
  }

  public function findOneForUser($user_id, $id, $type)
  {
    $query = $this->createQuery()->where('id = ?', $id);

    if ('received' == $type) {
      $query->andWhere('receiver = ?', $user_id);
    }
    elseif ('sent' == $type) {
      $query->andWhere('sender = ?', $user_id);
    }
    else {
      $query->andWhere('1 <> 1');
    }

    return $query->fetchOne();
  }
}