<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostComment extends BasePostComment
{
   public function read(Post $post = null) {
    if (is_null($post)) {
      $post = $this->Post;
    }

    $user = sfContext::getInstance()->getUser();
    if (!$user->isCommentUnread($post, $this)) {
      return true;
    }

    $ids = sfContext::getInstance()->getUser()->getAttribute('read_post_comments', array());
    $ids[$post->id][] = $this->id;
    sfContext::getInstance()->getUser()->setAttribute('read_post_comments', $ids);
  }
}