<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostCommentTable extends Doctrine_Table {

  public function killComment($id = null)
  {
    if (!$id)
      return false;

    $q = $this->createQuery('c')
        ->delete()
        ->where('c.id = ?', $id);

    return ($q->execute()) ? true : false;
  }

}