<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RegionTable extends Doctrine_Table
{
  public function createQuery($alias = '') {
    return parent::createQuery($alias)->orderBy('position');
  }
}