<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SitemapSeoData extends BaseSitemapSeoData
{
  public static function getSeoDescription($type, $cid, $region_id, $regionnode = null, $street = null){
    if(!is_null($cid)){
      $data   = Doctrine::getTable('SitemapSeoData')->find($cid);
      $region = Doctrine::getTable('Region')->find($region_id);
      
      switch ($data->level) {
        case 'city':
        case 'district':
        case 'village':
          $replace[] = $regionnode->full_name;
          break;
        case 'street':
          $replace[]  = $street;
          break;
        case 'region':
          $replace[] = $region->name;
          break;

      }    

      switch ($data->level) {
        case 'city': 
          $pattern[] = '/\[город([А-я])*\]/';
          break;
        case 'street':
          $pattern[] = '/\[улиц([А-я])*\]/'; 
          $pattern[] = '/\[город([А-я])*\]/';
          if (null == $regionnode) {
            $replace[]  = 'в ' . $region->full_name_prepositional;
          }else {
            $replace[]  = 'в ' . $regionnode->full_name_prepositional;
          }
          break;
        case 'village':
          $pattern[] = '/\[деревне или поселке\]/';
          break;
        case 'region':
          $pattern[] = '/\[регион([А-я])*\]/';
          break;
        case 'district':
          $pattern[] = '/\[район([А-я])*\]/';
          break;
      }

      $description = preg_replace($pattern, $replace, $data->content);
      
      if ($type == 'commercial-sale' || $type == 'commercial-rent') {
        $formField = Doctrine::getTable('FormField')->find(45);
        $choices = $formField->getChoices(false);
        foreach ($choices as $choice) {
          $description = str_replace('[вид недвижимости]', $choice, $description);
        }
      }

      return $description;
    }
    return false;
  }
}