<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Street extends BaseStreet
{
  public function getUnique()
  {
    return md5($this->regionnode_id.$this->name);
  }

  public function getFullName () {
    return Regionnode::formatName($this->name, $this->socr);
  }
}