<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserSourcesLink extends BaseUserSourcesLink
{
  const
    TYPE_MAIN       = 1,
    TYPE_IRR        = 2,
    TYPE_MIRKVARTIR = 3,

    STATUS_ACTIVE   = 'active',
    STATUS_BANNED   = 'banned',
    STATUS_RESTORED = 'restored',
    STATUS_NOT_PAID = 'not-paid',

//    FREQUENCY_1     = 2,
//    FREQUENCY_2     = 6,
    FREQUENCY_3     = 12,
    FREQUENCY_4     = 24;

  public static
    $types = array(
      self::TYPE_MAIN       => 'Формат Место.ру'
    ),
    $frequencies = array(
//      self::FREQUENCY_1 =>  '2 часа',
//      self::FREQUENCY_2 =>  '6 часов',
      self::FREQUENCY_3 =>  '12 часов',
      self::FREQUENCY_4 =>  '24 часа'
    );

  public function getTypeName()
  {
    return self::$types[$this->type];
  }

  public function getFileTypeName()
  {
    return ImportFile::$types[$this->file_type];
  }
}