<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserInfo extends BaseUserInfo
{
  public function getFieldNames () {
    $names = array(
      'additional_phone' => 'Дополнительный телефон',
      'about'            => 'О компании',
      'specialities'     => 'Специализация',
      'regions'          => 'Регионы работы',
      'experience'       => 'Время работы на рынке недвижимости',
      'advantage'        => 'Преимущества работы с компанией',
      'site'             => 'Адрес сайта',
    );

    switch ($this->User->type) {
      case 'employee':
        $names['about'] = 'О себе';
        $names['experience'] = 'Опыт работы риэлтором';
        unset($names['advantage']);
        break;

      case 'realtor':
        $names['about'] = 'О себе';
        $names['experience'] = 'Опыт работы риэлтором';
        $names['advantage'] = 'Преимущества работы с частным риэлтором';
        break;

      case 'owner':
        $names['about'] = 'О себе';
        unset($names['specialities'], $names['regions'], $names['experience'], $names['advantage']);
        break;
    }

    return $names;
  }

  public function getFieldName ($field) {
    $names = $this->getFieldNames();
    return isset($field) ? $names[$field] : null;
  }

  public function getEmailConfirmed () {
    return $this->email_confirmation == 1;
  }

  public function getSiteLink() {
    return (strpos($this->site, 'http://') === false ? 'http://' : '') . $this->site;
  }
}