generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Analytics
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          analytics
    with_doctrine_route:     1

    config:
      actions:
        _edit: { credentials: [redactor-analytics-actions] }
        _delete: { credentials: [redactor-analytics-delete] }
      fields:  ~
      list:
        fields:
          title_photo: {label: Изображение}
          title_and_lid: {label: Заголовок и Анонс}
        display: [_title_photo, _title_and_lid]
        sort: [created_at, desc]
        title: Аналитика        
        max_per_page: 10
      filter:
        class: AnalyticsFormFilter
      form:    ~
      edit:
        title: Редактирование аналитической статьи "%%title%%" от %%created_at%%
      new:
        title: Добавление аналитической статьи