77:
  САО:
    apartament-sale: ~
    apartament-rent: ~
    house-sale: ~
    house-rent: ~
    commercial-sale: ~
    commercial-rent: ~
  СВАО:
    apartament-sale: ~
    apartament-rent: ~
    house-sale: ~
    house-rent: ~
    commercial-sale: ~
    commercial-rent: ~
  ВАО:
    apartament-sale: ~
    apartament-rent: ~
    house-sale: ~
    house-rent: ~
    commercial-sale: ~
    commercial-rent: ~
  ЮВАО:
    apartament-sale: ~
    apartament-rent: ~
    house-sale: ~
    house-rent: ~
    commercial-sale: ~
    commercial-rent: ~
  ЮАО:
    apartament-sale: ~
    apartament-rent: ~
    house-sale: ~
    house-rent: ~
    commercial-sale: ~
    commercial-rent: ~
  ЮЗАО:
    apartament-sale: ~
    apartament-rent: ~
    house-sale: ~
    house-rent: ~
    commercial-sale: ~
    commercial-rent: ~
  ЗАО:
    apartament-sale: ~
    apartament-rent: ~
    house-sale: ~
    house-rent: ~
    commercial-sale: ~
    commercial-rent: ~
  СЗАО:
    apartament-sale: ~
    apartament-rent: ~
    house-sale: ~
    house-rent: ~
    commercial-sale: ~
    commercial-rent: ~
  ЦАО:
    apartament-sale: ~
    apartament-rent: ~
    house-sale: ~
    house-rent: ~
    commercial-sale: ~
    commercial-rent: ~