all:
  adygeya: 1
  bashkortostan: 2
  buryatiya: 3
  altay: 4
  dagestan: 5
  ingushetiya: 6
  kabardinobalkariya: 7
  kalmykiya: 8
  karachaevocherkessiya: 9
  kareliya: 10
  komi: 11
  mariy: 12
  mordoviya: 13
  saha: 14
  severnaya: 15
  tatarstan: 16
  tyva: 17
  udmurtiya: 18
  hakasiya: 19
  chechnya: 20
  chuvashiya: 21
  altayskiy: 22
  krasnodarskiy: 23
  krasnoyarskiy: 24
  primorskiy: 25
  stavropolskiy: 26
  habarovskiy: 27
  amurskaya: 28
  arhangelskaya: 29
  astrahanskaya: 30
  belgorodskaya: 31
  bryanskaya: 32
  vladimirskaya: 33
  volgogradskaya: 34
  vologodskaya: 35
  voronezhskaya: 36
  ivanovskaya: 37
  irkutskaya: 38
  kaliningradskaya: 39
  kaluzhskaya: 40
  kamchatskiy: 41
  kemerovskaya: 42
  kirovskaya: 43
  kostromskaya: 44
  kurganskaya: 45
  kurskaya: 46
  leningradskaya: 47
  lipetskaya: 48
  magadanskaya: 49
  v-podmoskovie: 50
  murmanskaya: 51
  nizhegorodskaya: 52
  novgorodskaya: 53
  novosibirskaya: 54
  omskaya: 55
  orenburgskaya: 56
  orlovskaya: 57
  penzenskaya: 58
  permskiy: 59
  pskovskaya: 60
  rostovskaya: 61
  ryazanskaya: 62
  samarskaya: 63
  saratovskaya: 64
  sahalinskaya: 65
  sverdlovskaya: 66
  smolenskaya: 67
  tambovskaya: 68
  tverskaya: 69
  tomskaya: 70
  tulskaya: 71
  tyumenskaya: 72
  ulyanovskaya: 73
  chelyabinskaya: 74
  zabaykalskiy: 75
  yaroslavskaya: 76
  www: 77
  peterburg: 78
  evreyskaya: 79
  nenetskiy: 83
  hantymansiyskiy: 86
  chukotskiy: 87
  yamalonenetskiy: 89
  crimea: 90
