all:
  - www
  - .ru
  - .com
  - .info
  - .net
  - ',org'
  - .su
  - архипиздрит
  - балобол
  - бздение
  - бздеть
  - бздех
  - бзднуть
  - бздун
  - бздунья
  - бздюха
  - бляд
  - блябу
  - блябуду
  - блядун
  - блядунья
  - блядь
  - блядюга
  - вафел
  - взьебка
  - взьебывать
  - взъебывать
  - выблядок
  - выблядыш
  - выебать
  - выпердеть
  - высраться
  - выссаться
  - гнида
  - говенка
  - говенный
  - говешка
  - говназия
  - говнецо
  - говно
  - говноед
  - говночист
  - говнюк
  - говнюха
  - говнядина
  - говняк
  - говняный
  - говнять
  - гондон
  - гандон
  - даун
  - дебил
  - долбоеб
  - дрисня
  - дрист
  - дристать
  - дристануть
  - дристун
  - дристуха
  - дрочена
  - дрочила
  - дрочилка
  - дрочить
  - дрочка
  - дурак
  - дура
  - ебало
  - ебальник
  - ебан
  - ебануть
  - ебаный
  - ебарь
  - ебатория
  - ебать
  - ебаться
  - ебец
  - ебливый
  - ебля
  - ебнуть
  - ебнуться
  - ебня
  - ебун
  - елда
  - елдак
  - елдачить
  - заговнять
  - задрачивать
  - задристать
  - задрота
  - заеба
  - заебанец
  - заебать
  - заебаться
  - заебываться
  - залупа
  - залупаться
  - залупить
  - залупиться
  - замудохаться
  - засерун
  - засеря
  - засерать
  - засирать
  - засранец
  - засрун
  - захуячить
  - злоебучий
  - изговнять
  - изговняться
  - конча
  - конченный
  - лох
  - лошара
  - лошок
  - манда
  - мандавошка
  - мандей
  - мандеть
  - мандища
  - мандюк
  - минет
  - минетчик
  - минетчица
  - мокрохвостка
  - мокрощелка
  - мразь
  - мудак
  - муде
  - мудеть
  - мудила
  - мудистый
  - мудня
  - мудоеб
  - мудозвон
  - набздеть
  - наговнять
  - надристать
  - надрочить
  - наебать
  - наебнуться
  - наебывать
  - насрать
  - нахуйник
  - обдристаться
  - обдристаться
  - обосранец
  - обосрать
  - обосцать
  - обосцаться
  - обсирать
  - опездал
  - опизде
  - отпиздячить
  - отпороть
  - очко
  - очкун
  - очкарь
  - охуевательский
  - охуевать
  - охуевающий
  - охуеть
  - охуительный
  - охуячивать
  - охуячить
  - падонок
  - педрик
  - педрило
  - пердеж
  - пердение
  - пердеть
  - пердильник
  - перднуть
  - пердун
  - пердунец
  - пердунина
  - пердунья
  - пердуха
  - пердь
  - передок
  - пернуть
  - пидор
  - пизда
  - пиздануть
  - пизденка
  - пиздеть
  - пиздить
  - пиздища
  - пиздобратия
  - пиздоватый
  - пиздорванец
  - пиздорванка
  - пиздострадатель
  - пиздун
  - пиздюга
  - пиздюк
  - пиздячить
  - писять
  - пнх
  - подговнять
  - подъебнуться
  - поебать
  - порно
  - посрать
  - проблядь
  - проебать
  - промандеть
  - промудеть
  - пропиздеть
  - пропиздячить
  - проститутка
  - придурок
  - раздолбай
  - разъеба
  - разъебай
  - распиздай
  - распиздеться
  - распиздяй
  - распроеть
  - сволочь
  - сволота
  - сговнять
  - секель
  - серун
  - серька
  - сикель
  - сирать
  - сирывать
  - сосать
  - соси
  - спиздить
  - срака
  - сраный
  - сранье
  - срать
  - срун
  - ссака
  - ссышь
  - сука
  - суходрочка
  - сцышь
  - сцание
  - сцать
  - сцука
  - сцуль
  - сцыха
  - сыкун
  - тёлка
  - ублюдок
  - урод
  - уроды
  - уродка
  - уродина
  - усраться
  - ушлепок
  - хер
  - херня
  - херовина
  - херовый
  - хитрожопый
  - хуевина
  - хуевый
  - хуек
  - хуепромышленник
  - хуерик
  - хуесос
  - хуище
  - хуй
  - хуйня
  - хуйрик
  - хуля
  - хуякать
  - хуякнуть
  - чмо
  - чмырь
  - чмошник
  - целка
  - шалава
  - шлюха
  - fuck
  - 'fuck you'
  - блядота
