-
  'Бесплатные объявления о продаже  недвижимости в [районе]':
    type: ''
    title: 'Подать бесплатно частное объявление о продаже  недвижимости в [районе], газета, доска объявлений недвижимость из рук в руки в [районе]'
    h1: 'Доска бесплатных объявлений о продаже недвижимости в [районе]'
-
  'Бесплатные объявления о продаже  недвижимости в [городе]':
    type: ''
    title: 'Подать бесплатно частное объявление о продаже  недвижимости в [городе], газета, доска объявлений недвижимость из рук в руки в [городе]'
    h1: 'Доска бесплатных объявлений о продаже недвижимости в [городе]'
-
  'Купить квартиру в [регионе], продать квартиру в [регионе]':
    type: apartament-sale
    title: 'Купить квартиру в [регионе], продажа квартиры в [регионе], фото и цены на квартиры в [регионе], рынок вторичного жилья в [регионе]'
    h1: 'Купить квартиру в [регионе], продажа квартиры в [регионе]'
-
  'Купить комнату в [регионе], продать комнату в [регионе]':
    type: apartament-sale
    title: 'Купить комнату в [регионе], продажа комнаты в [регионе], цены, стоимость комнаты в [регионе]'
    h1: 'Купить комнату в [регионе], продажа комнаты в [регионе]'
-
  'Купить однокомнатную квартиру в [регионе], продать однокомнатную квартиру в [регионе]':
    type: apartament-sale
    title: 'Купить однокомнатную квартиру в [регионе], продажа однокомнатной квартиры в [регионе], цены, стоимость однокомнатной квартиры в [регионе]'
    h1: 'Купить однокомнатную квартиру в [регионе], продажа однокомнатной квартиры в [регионе]'
-
  'Купить двухкомнатную квартиру в [регионе], продать двухкомнатную квартиру в [регионе]':
    type: apartament-sale
    title: 'Купить двухкомнатную квартиру в [регионе], продажа двухкомнатной квартиры в [регионе], цены, стоимость двухкомнатной квартиры в [регионе]'
    h1: 'Купить двухкомнатную квартиру в [регионе], продажа двухкомнатной квартиры в [регионе]'
-
  'Купить трехкомнатную квартиру в [регионе], продать трехкомнатную квартиру в [регионе]':
    type: apartament-sale
    title: 'Купить трехкомнатную квартиру в [регионе], продажа трехкомнатной квартиры в [регионе], цены, стоимость трехкомнатной квартиры в [регионе]'
    h1: 'Купить трехкомнатную квартиру в [регионе], продажа трехкомнатной квартиры в [регионе]'
-
  'Купить квартиру в [городе], продать квартиру в [городе]':
    type: apartament-sale
    title: 'Купить квартиру в [городе], продажа квартиры в [городе], фото и цены на квартиры в [городе], рынок вторичного жилья в [городе]'
    h1: 'Купить квартиру в [городе], продажа квартиры в [городе]'
-
  'Купить комнату в [городе], продать комнату в [городе]':
    type: apartament-sale
    title: 'Купить комнату в [городе], продажа комнаты в [городе], цены, стоимость комнаты в [городе]'
    h1: 'Купить комнату в [городе], продажа комнаты в [городе]'
-
  'Купить однокомнатную квартиру в [городе], продать однокомнатную квартиру в [городе]':
    type: apartament-sale
    title: 'Купить однокомнатную квартиру в [городе], продажа однокомнатной квартиры в [городе], цены, стоимость однокомнатной квартиры в [городе]'
    h1: 'Купить однокомнатную квартиру в [городе], продажа однокомнатной квартиры в [городе]'
-
  'Купить двухкомнатную квартиру в [городе], продать двухкомнатную квартиру в [городе]':
    type: apartament-sale
    title: 'Купить двухкомнатную квартиру в [городе], продажа двухкомнатной квартиры в [городе], цены, стоимость двухкомнатной квартиры в [городе]'
    h1: 'Купить двухкомнатную квартиру в [городе], продажа двухкомнатной квартиры в [городе]'
-
  'Купить трехкомнатную квартиру в [городе], продать трехкомнатную квартиру в [городе]':
    type: apartament-sale
    title: 'Купить трехкомнатную квартиру в [городе], продажа трехкомнатной квартиры в [городе], цены, стоимость трехкомнатной квартиры в [городе]'
    h1: 'Купить трехкомнатную квартиру в [городе], продажа трехкомнатной квартиры в [городе]'
-
  'Купить квартиру в [районе], продать квартиру в [районе]':
    type: apartament-sale
    title: 'Купить квартиру в [районе], продажа квартиры в [районе], фото и цены на квартиры в [районе], рынок вторичного жилья в [районе]'
    h1: 'Купить квартиру в [районе], продажа квартиры в [районе]'
-
  'Купить комнату в [районе], продать комнату в [районе]':
    type: apartament-sale
    title: 'Купить комнату в [районе], продажа комнаты в [районе], цены, стоимость комнаты в [районе]'
    h1: 'Купить комнату в [районе], продажа комнаты в [районе]'
-
  'Купить однокомнатную квартиру в [районе], продать однокомнатную квартиру в [районе]':
    type: apartament-sale
    title: 'Купить однокомнатную квартиру в [районе], продажа однокомнатной квартиры в [районе], цены, стоимость однокомнатной квартиры в [районе]'
    h1: 'Купить однокомнатную квартиру в [районе], продажа однокомнатной квартиры в [районе]'
-
  'Купить двухкомнатную квартиру в [районе], продать двухкомнатную квартиру в [районе]':
    type: apartament-sale
    title: 'Купить двухкомнатную квартиру в [районе], продажа двухкомнатной квартиры в [районе], цены, стоимость двухкомнатной квартиры в [районе]'
    h1: 'Купить двухкомнатную квартиру в [районе], продажа двухкомнатной квартиры в [районе]'
-
  'Купить трехкомнатную квартиру в [районе], продать трехкомнатную квартиру в [районе]':
    type: apartament-sale
    title: 'Купить трехкомнатную квартиру в [районе], продажа трехкомнатной квартиры в [районе], цены, стоимость трехкомнатной квартиры в [районе]'
    h1: 'Купить трехкомнатную квартиру в [районе], продажа трехкомнатной квартиры в [районе]'
-
  'Аренда квартиры в [регионе], снять квартиру в [регионе]':
    type: apartament-rent
    title: 'Аренда квартир в [регионе] дешево, снять квартиру в [регионе] недорого, цена сдачи квартиры в [регионе], стоимость аренды квартиры в [регионе] на месяц'
    h1: 'Аренда квартиры в [регионе], снять квартиру в [регионе]'
-
  'Аренда квартиры в [районе], снять квартиру в [районе]':
    type: apartament-rent
    title: 'Аренда квартир в [районе] дешево, снять квартиру в [районе] недорого, цена сдачи квартиры в [районе], стоимость аренды квартиры в [районе] на месяц'
    h1: 'Аренда квартиры в [районе], снять квартиру в [районе]'
-
  'Аренда комнаты в [районе], снять комнату в [районе]':
    type: apartament-rent
    title: 'Аренда комнат в [районе] дешево, снять комнату в [районе] недорого, цена сдачи комнаты в [районе], стоимость аренды комнаты в [районе] на месяц'
    h1: 'Аренда комнаты в [районе], снять комнату в [районе]'
-
  'Аренда однокомнатной квартиры в [районе], снять однокомнатную квартиру в [районе]':
    type: apartament-rent
    title: 'Аренда однокомнатной квартиры в [районе], снять однокомнатную квартиру в [районе]'
    h1: 'Аренда однокомнатной квартиры в [районе], снять однокомнатную квартиру в [районе]'
-
  'Аренда квартиры в [городе], снять квартиру в [городе]':
    type: apartament-rent
    title: 'Аренда квартир в [городе] дешево, снять квартиру в [городе] недорого, цена сдачи квартиры в [городе], стоимость аренды квартиры в [городе] на месяц'
    h1: 'Аренда квартиры в [городе], снять квартиру в [городе]'
-
  'Аренда комнаты в [городе], снять комнату в [городе]':
    type: apartament-rent
    title: 'Аренда комнат в [городе] дешево, снять комнату в [городе] недорого, цена сдачи комнаты в [городе], стоимость аренды комнаты в [городе] на месяц'
    h1: 'Аренда комнаты в [городе], снять комнату в [городе]'
-
  'Аренда однокомнатной квартиры в [городе], снять однокомнатную квартиру в [городе]':
    type: apartament-rent
    title: 'Аренда однокомнатной квартиры в [городе], снять однокомнатную квартиру в [городе]'
    h1: 'Аренда однокомнатной квартиры в [городе], снять однокомнатную квартиру в [городе]'
-
  'Купить квартиру на [улице] [города], продать квартиру на [улице] [города]':
    type: apartament-sale
    title: 'Купить квартиру на [улице] [города], продать квартиру на [улице] [города]'
    h1: 'Купить квартиру на [улице] [города], продать квартиру на [улице] [города]'
-
  'Аренда квартиры на [улице] [города], снять квартиру на [улице] [города]':
    type: apartament-rent
    title: 'Аренда квартиры без посредников на [улице] [города], снять квартиру на месяц на [улице] [города]'
    h1: 'Аренда квартиры на [улице] [города], снять квартиру на [улице] [города]'
-
  'Купить квартиру в [деревне или поселке], продать квартиру в [деревне или поселке]':
    type: apartament-sale
    title: 'Купить квартиру в [деревне или поселке], продать квартиру в [деревне или поселке]'
    h1: 'Купить квартиру в [деревне или поселке], продать квартиру в [деревне или поселке]'
-
  'Аренда квартиры в [деревне или поселке], снять квартиру в [деревне или поселке]':
    type: apartament-rent
    title: 'Аренда квартиры без посредников в [деревне или поселке], снять квартиру на месяц в [деревне или поселке]'
    h1: 'Аренда квартиры в [деревне или поселке], снять квартиру в [деревне или поселке]'
-
  'Купить коммерческую недвижимость в [регионе], продажа коммерческой недвижимости в [регионе]':
    type: commercial-sale
    title: 'Купить коммерческую недвижимость от собственника в [регионе], цены, продажа коммерческой недвижимости без посредников в [регионе], стоимость'
    h1: 'Купить коммерческую недвижимость в [регионе], продажа коммерческой недвижимости в [регионе]'
-
  'Купить [вид недвижимости] в [регионе], продать [вид недвижимости] в [регионе]':
    type: ''
    title: 'Купить [вид недвижимости] в [регионе],  продажа [вид недвижимости] в [регионе]'
    h1: 'Купить [вид недвижимости] в [регионе],  продажа [вид недвижимости] в [регионе]'
-
  'Аренда коммерческой недвижимости в [регионе], снять коммерческую недвижимость в [регионе]':
    type: commercial-rent
    title: 'Купить коммерческую недвижимость от собственника в [регионе], цены, продажа коммерческой недвижимости без посредников в [регионе], стоимость'
    h1: 'Купить коммерческую недвижимость в [регионе], продажа коммерческой недвижимости в [регионе]'
-
  'Аренда [вид недвижимости] в [регионе], снять [вид недвижимости] в [регионе]':
    type: ''
    title: 'Аренда  [вид недвижимости] в [регионе] без посредников, снять  [вид недвижимости] в [регионе], стоимость'
    h1: 'Аренда  [вид недвижимости] в [регионе], снять  [вид недвижимости] в [регионе]'
-
  'Купить коммерческую недвижимость в [городе], продажа коммерческой недвижимости в [городе]':
    type: commercial-sale
    title: 'Купить коммерческую недвижимость от собственника в [городе], цены, продажа коммерческой недвижимости без посредников в [городе], стоимость'
    h1: 'Купить коммерческую недвижимость в [городе], продажа коммерческой недвижимости в [городе]'
-
  'Купить [вид недвижимости] в [городе], продать [вид недвижимости] в [городе]':
    type: ''
    title: 'Купить [вид недвижимости] в [городе],  продажа [вид недвижимости] в [городе]'
    h1: 'Купить [вид недвижимости] в [городе],  продажа [вид недвижимости] в [городе]'
-
  'Аренда коммерческой недвижимости в [городе], снять коммерческую недвижимость в [городе]':
    type: commercial-rent
    title: 'Купить коммерческую недвижимость от собственника в [городе], цены, продажа коммерческой недвижимости без посредников в [городе], стоимость'
    h1: 'Купить коммерческую недвижимость в [городе], продажа коммерческой недвижимости в [городе]'
-
  'Аренда [вид недвижимости] в [городе], снять [вид недвижимости] в [городе]':
    type: ''
    title: 'Аренда  [вид недвижимости] в [городе] без посредников, снять  [вид недвижимости] в [городе], стоимость'
    h1: 'Аренда  [вид недвижимости] в [городе], снять  [вид недвижимости] в [городе]'
-
  'Купить коммерческую недвижимость в [районе], продажа коммерческой недвижимости в [районе]':
    type: commercial-sale
    title: 'Купить коммерческую недвижимость от собственника в [районе], цены, продажа коммерческой недвижимости без посредников в [районе], стоимость'
    h1: 'Купить коммерческую недвижимость в [районе], продажа коммерческой недвижимости в [районе]'
-
  'Купить [вид недвижимости] в [районе], продать [вид недвижимости] в [районе]':
    type: ''
    title: 'Купить [вид недвижимости] в [районе], стоимость, продажа [вид недвижимости] в [районе]'
    h1: 'Купить [вид недвижимости] в [районе],  продажа [вид недвижимости] в [районе]'
-
  'Аренда коммерческой недвижимости в [районе], снять коммерческую недвижимость в [районе]':
    type: commercial-rent
    title: 'Купить коммерческую недвижимость от собственника в [районе], цены, продажа коммерческой недвижимости без посредников в [районе], стоимость'
    h1: 'Купить коммерческую недвижимость в [районе], продажа коммерческой недвижимости в [районе]'
-
  'Аренда [вид недвижимости] в [районе], снять [вид недвижимости] в [районе]':
    type: ''
    title: 'Аренда  [вид недвижимости] в [районе] без посредников, снять  [вид недвижимости] в [районе], стоимость'
    h1: 'Аренда  [вид недвижимости] в [районе], снять  [вид недвижимости] в [районе]'
-
  'Купить коммерческую недвижимость на [улице] [города], продажа коммерческой недвижимости на [улице] [города]':
    type: commercial-sale
    title: 'Купить коммерческую недвижимость от собственника на [улице] [города], цены, продажа коммерческой недвижимости без посредников на [улице] [города], стоимость'
    h1: 'Купить коммерческую недвижимость на [улице] [города], продажа коммерческой недвижимости на [улице] [города]'
-
  'Купить [вид недвижимости] на [улице] [города], продать [вид недвижимости] на [улице] [города]':
    type: ''
    title: '[вид недвижимости] на [улице] [города]'
    h1: 'Купить [вид недвижимости] на [улице] [города],  продать [вид недвижимости] на [улице] [города]'
-
  'Аренда коммерческой недвижимости на [улице] [города], снять коммерческую недвижимость на [улице] [города]':
    type: commercial-rent
    title: 'Купить коммерческую недвижимость от собственника на [улице] [города], цены, продажа коммерческой недвижимости без посредников на [улице] [города], стоимость'
    h1: 'Купить коммерческую недвижимость на [улице] [города], продажа коммерческой недвижимости на [улице] [города]'
-
  'Аренда [вид недвижимости] на [улице] [города], снять [вид недвижимости] на [улице] [города]':
    type: ''
    title: 'Аренда  [вид недвижимости] на [улице] [города]'
    h1: 'Аренда  [вид недвижимости] на [улице] [города]'
-
  'Купить дом, дачу, коттедж, таунхаус  в [регионе], продажа дома, дачи, коттеджа, таунхауса в [регионе]':
    type: house-sale
    title: 'Купить дом, дачу, коттедж, таунхаус  в [регионе] с фото, продажа дома, дачи, коттеджа, таунхауса  в [регионе] недорого и без посредников'
    h1: 'Купить дом, дачу, коттедж, таунхаус  в [регионе], продажа  дома, дачи, коттеджа, таунхаус в [регионе]'
-
  'Купить земельный участок  в [регионе], продажа земельного участка в [регионе]':
    type: house-sale
    title: 'Купить земельный участок в [регионе] дешево, продажа участка дачной земли в [регионе] недорого, цены и стоимость участков в [регионе]'
    h1: 'Купить земельный участок  в [регионе], продажа земельного участка в [регионе]'
-
  'Аренда дома, дачи, коттеджа  в [регионе], снять дом, дачу, коттедж  в [регионе]':
    type: house-rent
    title: 'Аренда загородного дома, дачи, коттеджа на сутки  в [регионе] без посредников, снять дом, дачу, коттедж  в [регионе] на выходные недорого'
    h1: 'Аренда дома,дачи, коттеджа  в [регионе], снять дом, дачу, коттедж  в [регионе]'
-
  'Аренда земельного участка  в [регионе], снять земельный участок в [регионе]':
    type: house-rent
    title: 'Аренда земельного участка  в [регионе], снять садовый участок в [регионе]'
    h1: 'Аренда земельного участка  в [регионе], снять садовый участок в [регионе]'
-
  'Купить дом, дачу, коттедж, таунхаус  в [городе], продажа дома, дачи, коттеджа, таунхауса в [городе]':
    type: house-sale
    title: 'Купить дом, дачу, коттедж, таунхаус  в [городе] дешево (фото), продажа дома, дачи, коттеджа, таунхауса  в [городе] недорого и без посредников'
    h1: 'Купить дом, дачу, коттедж, таунхаус  в [городе], продажа  дома, дачи, коттеджа, таунхауса в [городе]'
-
  'Купить земельный участок  в [городе], продажа земельного участка в [городе]':
    type: house-sale
    title: 'Купить земельный участок в [городе] дешево, продажа участка дачной земли в [городе] недорого, цены и стоимость участков в [городе]'
    h1: 'Купить земельный участок  в [городе], продажа земельного участка в [городе]'
-
  'Аренда дома, дачи, коттеджа  в [городе], снять дом, дачу, коттедж  в [городе]':
    type: house-rent
    title: 'Аренда загородного дома, дачи, коттеджа на сутки  в [городе] без посредников, снять дом, дачу, коттедж  в [городе] на выходные недорого'
    h1: 'Аренда дома,дачи, коттеджа  в [городе], снять дом, дачу, коттедж  в [городе]'
-
  'Аренда земельного участка  в [городе], снять земельный участок в [городе]':
    type: house-rent
    title: 'Аренда земельного участка  в [городе], снять садовый участок в [городе]'
    h1: 'Аренда земельного участка  в [городе], снять садовый участок в [городе]'
-
  'Купить дом, дачу, коттедж, таунхаус в [деревне или поселке], продажа дома, дачи, коттеджа, таунхауса в [деревне или поселке]':
    type: house-sale
    title: 'Купить дом, дачу, коттедж, таунхаус в [деревне или поселке], продажа дома, дачи, коттеджа, таунхауса в [деревне или поселке]'
    h1: 'Купить дом, дачу, коттедж, таунхаус в [деревне или поселке], продажа дома, дачи, коттеджа, таунхауса в [деревне или поселке]'
-
  'Купить земельный участок  в [деревне или поселке], продажа земельного участка в [деревне или поселке]':
    type: house-sale
    title: 'Купить земельный участок в [деревне или поселке] дешево, продажа участка дачной земли в [деревне или поселке] недорого, цены и стоимость участков в [деревне или поселке]'
    h1: 'Купить земельный участок  в [деревне или поселке], продажа земельного участка в [деревне или поселке]'
-
  'Аренда дома, дачи, коттеджа  в [деревне или поселке], снять дом, дачу, коттедж  в [деревне или поселке]':
    type: house-rent
    title: 'Аренда загородного дома, дачи, коттеджа на сутки  в [деревне или поселке], снять дом, дачу, коттедж на выходные  в [деревне или поселке]'
    h1: 'Аренда дома,дачи, коттеджа  в [деревне или поселке], снять дом, дачу, коттедж  в [деревне или поселке]'
-
  'Аренда земельного участка  в [деревне или поселке], снять земельный участок в [деревне или поселке]':
    type: house-rent
    title: 'Аренда земельного участка  в [деревне или поселке], снять садовый участок в [деревне или поселке]'
    h1: 'Аренда земельного участка  в [деревне или поселке], снять садовый участок в [деревне или поселке]'
