generator:
  class: sfDoctrineGenerator
  param:
    model_class:           News
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          news
    with_doctrine_route:     1

    config:
      actions:
        _edit: { credentials: [redactor-news-actions] }
        _delete: { credentials: [redactor-news-delete] }
      fields:  ~
      list:
        fields:
          title_photo: {label: Изображение}
          title_and_lid: {label: Заголовок и Анонс}
          created_at: { label: Дата создания }
        display: [_title_photo, _title_and_lid, created_at]
        sort: [created_at, desc]
        title: Новости
        max_per_page: 10
      filter:
        class: NewsFormFilter
      form:    ~
      edit:
        title: Редактирование новости "%%title%%" от %%created_at%%
      new:
        title: Добавление новости