<?php
/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class AdduserinfoMigration extends Doctrine_Migration
{
  public function up()
  {
    $this->createTable('user_info',
      array(
        'user_id' => array(
        'type' => 'integer',
        'primary' => true,
        'unsigned' => true,
        'length' => 4,
        ),
        'additional_phone' => array(
        'type' => 'string',
        'length' => 18,
        ),
        'about' => array(
        'type' => 'string',
        'length' => NULL,
        ),
        'specialities' => array(
        'type' => 'string',
        'length' => NULL,
        ),
        'regions' => array(
        'type' => 'string',
        'length' => NULL,
        ),
        'experience' => array(
        'type' => 'string',
        'length' => NULL,
        ),
        'advantage' => array(
        'type' => 'string',
        'length' => NULL,
        ),
        'site' => array(
        'type' => 'string',
        'length' => 100,
        ),
      ),
      array(
        'indexes' => array(),
        'primary' => array(
          0 => 'user_id',
        ),
      )
    );
  }

  public function down()
  {
    $this->dropTable('user_info');
  }
}