<?php
/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class Adduserinfo2Migration extends Doctrine_Migration
{
  public function up()
  {
    $users=  Doctrine::getTable('User')->findAll();
    foreach ($users as $user) {
      $user->Info = new UserInfo();
      $user->save();
    }
  }

  public function down()
  {
    
  }
}