<?php
/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class AddRatingMigration extends Doctrine_Migration
{
  public function up()
  {
    $this->addColumn('form_field', 'rating', 'integer', array(
      'length'   => 1,
      'unsigned' => true,
    ));
    $this->addColumn('lot', 'rating', 'integer', array(
      'length'   => 1,
      'unsigned' => true,
    ));
    $this->addColumn('user', 'rating', 'integer', array(
      'length'   => 1,
      'unsigned' => true,
    ));
  }

  public function down()
  {
    $this->removeColumn('form_field', 'rating');
    $this->removeColumn('lot', 'rating');
    $this->removeColumn('user', 'rating');
  }
}