<?php
/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class AddEmailconfirmationMigration extends Doctrine_Migration
{
  public function up()
  {
    $this->addColumn('user_info', 'email_confirmation', 'string', array('length' => 8));
  }

  public function down()
  {
    $this->removeColumn('user_info', 'email_confirmation');
  }
}