<?php
/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class AddRating2Migration extends Doctrine_Migration
{
  public function up()
  {
    $this->changeColumn('form_field', 'rating', 'integer', array(
      'length'   => 3,
      'unsigned' => true,
    ));
    $this->changeColumn('lot', 'rating', 'integer', array(
      'length'   => 3,
      'unsigned' => true,
    ));
    $this->changeColumn('user', 'rating', 'integer', array(
      'length'   => 3,
      'unsigned' => true,
    ));
  }

  public function down()
  {
    $this->changeColumn('form_field', 'rating', 'integer', array(
      'length'   => 1,
      'unsigned' => true,
    ));
    $this->changeColumn('lot', 'rating', 'integer', array(
      'length'   => 1,
      'unsigned' => true,
    ));
    $this->changeColumn('user', 'rating', 'integer', array(
      'length'   => 1,
      'unsigned' => true,
    ));
  }
}