<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddusersettingsMigration extends Doctrine_Migration
{
	public function up()
	{
		$this->createTable('user_settings', array(
             'user_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'unsigned' => true,
              'length' => 4,
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 30,
             ),
             'value' => 
             array(
              'type' => 'string',
              'length' => NULL,
             ),
             ), array(
             'indexes' => 
             array(
              'user_id_name' => 
              array(
              'fields' => 
              array(
               0 => 'user_id',
               1 => 'name',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'user_id',
             ),
             ));
	}

	public function down()
	{
		$this->dropTable('user_settings');
	}
}