<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddformadditionalheaderMigration extends Doctrine_Migration
{
	public function up()
	{
		$this->addColumn('form', 'show_additional_header', 'boolean', array());
	}

	public function down()
	{
		$this->removeColumn('form', 'show_additional_header');
	}
}