<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FixusersettingsMigration extends Doctrine_Migration
{
	public function up()
	{
		$this->dropConstraint('user_settings', 'PRIMARY', true);
		$this->removeIndex('user_settings', 'user_id_name');
    $this->createConstraint('user_settings', 'PRIMARY', array(
      'fields'  => array('user_id' => array(), 'name' => array()),
      'primary' => true,
    ));
	}

	public function down()
	{ }
}