<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddsessionMigration extends Doctrine_Migration
{
	public function up()
	{
		$this->createTable(
      'session', 
      array(
        'id' => array(
        'type' => 'string',
        'primary' => true,
        'length' => 32,
        ),
        'data' => array(
        'type' => 'string',
        'notnull' => true,
        'length' => NULL,
        ),
        'time' => array(
        'type' => 'integer',
        'notnull' => true,
        'length' => 8,
        ),
      ),
      array(
        'indexes' => array(),
        'primary' => array(
          0 => 'id',
        ),
      )
    );
	}

	public function down()
	{
		$this->dropTable('session');
	}
}