<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addusergroup2Migration extends Doctrine_Migration
{
  public function up()
  {
    $groups = array(
      array('Администраторы', serialize(UserGroup::$credentials)),
      array('Модераторы',     serialize(array('moder-access', 'moder-delete'))),
    );
    
    $conn = Doctrine_Manager::getInstance()->connection();
    foreach ($groups as $group) {
      $conn->execute('insert into user_group (name, credentials) values (?, ?)', $group);
    }
  }

  public function down()
  { }
}