<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addusergroup5Migration extends Doctrine_Migration
{
  public function up()
  {
    $conn = Doctrine_Manager::getInstance()->connection();
    $conn->execute('update user set group_id = ? where credential = ?', array(1, 'admin'));
    $conn->execute('update user set group_id = ? where credential = ?', array(2, 'moderator'));
    $this->removeColumn('user', 'credential');
  }

  public function down()
  {
    throw new Doctrine_Migration_IrreversibleMigrationException();
  }
}