<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addusergroup6Migration extends Doctrine_Migration
{
  public function up()
  {
    $conn = Doctrine_Manager::getInstance()->connection();
    $conn->execute('truncate session');
  }

  public function down()
  { }
}