<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddBlogMigration extends Doctrine_Migration
{
	public function up()
	{
		$this->createTable('blog', array(
      'id' =>
        array(
          'type' => 'integer',
          'unsigned' => true,
          'primary' => true,
          'autoincrement' => true,
          'length' => 3,
        ),
      'title' =>
        array(
          'type' => 'string',
          'fixed' => 1,
          'unique' => true,
          'notnull' => true,
          'length' => 100,
        ),
      'author_id' =>
        array(
          'type' => 'integer',
          'unsigned' => true,
          'unique' => true,
          'notnull' => true,
          'length' => 4,
        ),
    ), array(
      'indexes' =>
        array(
          'blog_title' =>
            array(
              'fields' =>
                array(
                  0 => 'title',
                ),
              'type' => 'unique',
            ),
        ),
    'primary' =>
      array(
        0 => 'id',
      ),
    ));
    
    $this->createForeignKey('blog', array(
      'local' => 'author_id',
      'foreign' => 'id',
      'foreignTable' => 'user',
      'onUpdate' => NULL,
      'onDelete' => 'CASCADE',
      'name' => 'blog_author_id',
    ));
	}

	public function down()
	{
    $this->dropForeignKey('blog', 'blog_author_id');
		$this->dropTable('blog');
	}
}