<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddPostMigration extends Doctrine_Migration
{
	public function up()
	{
		$this->createTable('post', array(
      'id' =>
        array(
          'type' => 'integer',
          'unsigned' => true,
          'primary' => true,
          'autoincrement' => true,
          'length' => 3,
        ),
      'post_type' =>
        array(
          'type' => 'enum',
          'values' =>
            array(
              0 => 'blog',
              1 => 'news',
              2 => 'events',
              3 => 'article',
              4 => 'analytics',
              5 => 'answer',
              6 => 'questionnaire',
            ),
          'notnull' => true,
          'length' => NULL,
        ),
      'created_at' =>
        array(
          'type' => 'timestamp',
          'notnull' => true,
          'length' => 25,
        ),
      'author_id' =>
        array(
          'type' => 'integer',
          'unsigned' => true,
          'notnull' => true,
          'length' => 4,
        ),
      'title' =>
        array(
          'type' => 'string',
          'notnull' => true,
          'length' => 255,
        ),
      'rating' =>
        array(
          'type' => 'integer',
          'unsigned' => true,
          'notnull' => true,
          'default' => 0,
          'length' => 3,
        ),
      'post_text' =>
        array(
          'type' => 'string',
          'notnull' => true,
          'length' => NULL,
        ),
      'status' =>
        array(
          'type' => 'enum',
          'values' =>
            array(
              0 => 'restricted',
              1 => 'publish',
              2 => 'not_publish',
              3 => 'inactive',
              4 => 'moderate',
            ),
          'notnull' => true,
          'default' => 'not_publish',
          'length' => NULL,
        ),
      'section' =>
        array(
          'type' => 'enum',
          'values' =>
            array(
              0 => 'Новости рынка',
              1 => 'Новости компании',
              2 => 'Новости портала',
            ),          
          'length' => NULL,
        ),
      'title_photo' =>
        array(
          'type' => 'string',
          'length' => 50,
        ),
      'title_photo_source' =>
        array(
          'type' => 'string',
          'length' => 200,
        ),
      'title_photo_source_url' =>
        array(
          'type' => 'string',
          'length' => 200,
        ),
      'blog_id' =>
        array(
          'type' => 'integer',
          'unsigned' => true,
          'length' => 3,
        ),
      'source' =>
        array(
          'type' => 'string',
          'length' => 400,
        ),
      'source_url' =>
        array(
          'type' => 'string',
          'length' => 200,
        ),
      'lid' =>
        array(
          'type' => 'string',
          'length' => 400,
        ),
      'subtitle' =>
        array(
          'type' => 'string',
          'length' => 255,
        ),
      'signature' =>
        array(
          'type' => 'string',
          'length' => 150,
        ),
      'less_count' =>
        array(
          'type' => 'integer',
          'default' => 0,
          'length' => 2,
        ),
      'is_primary' =>
        array(
          'type' => 'boolean',
          'default' => 0,
          'length' => 1,
          'notnull' => true,
        ),
      'on_main' =>
        array(
          'type' => 'boolean',
          'default' => 0,
          'length' => 1,
          'notnull' => true,
        ),
      'deleted' =>
        array(
          'default' => 0,
          'notnull' => true,
          'type' => 'boolean',
          'length' => 1,
        ),
      ), array(
        'indexes' =>
          array(
          'title_index' =>
            array(
              'fields' =>
                array(
                  0 => 'title',
                ),
            ),
          'created_at_index' =>
            array(
              'fields' =>
                array(
                  0 => 'created_at',
                ),
            ),
          'rating_index' =>
            array(
              'fields' =>
                array(
                  0 => 'rating',
                ),
            ),
          ),
        'primary' =>
          array(
            0 => 'id',
          ),
    ));

    $this->createForeignKey('post', array(
      'local' => 'author_id',
      'foreign' => 'id',
      'foreignTable' => 'user',
      'name' => 'post_author_id',
    ));
    $this->createForeignKey('post', array(
      'local' => 'blog_id',
      'foreign' => 'id',
      'foreignTable' => 'blog',
      'name' => 'post_blog_id',
    ));
	}

	public function down()
	{
    $this->dropForeignKey('post', 'post_author_id');
    $this->dropForeignKey('post', 'post_blog_id');
		$this->dropTable('post');
	}
}