<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddTag1Migration extends Doctrine_Migration
{
	public function up()
	{
		$this->createTable('tag', array(
      'id' =>
        array(
          'type' => 'integer',
          'unsigned' => true,
          'primary' => true,
          'autoincrement' => true,
          'length' => 3,
        ),
      'title' =>
        array(
          'type' => 'string',
          'fixed' => 1,
          'unique' => true,
          'notnull' => true,
          'length' => 64,
        ),
    ), array(
      'indexes' =>
        array(
        ),
      'primary' =>
        array(
          0 => 'id',
        ),
    ));
	}

	public function down()
	{
		$this->dropTable('tag');
	}
}