<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddPostComment1Migration extends Doctrine_Migration
{
	public function up()
	{
		$this->createTable('post_comment', array(
      'id' =>
        array(
          'type' => 'integer',
          'unsigned' => true,
          'primary' => true,
          'autoincrement' => true,
          'length' => 3,
        ),
      'user_id' =>
        array(
          'type' => 'integer',
          'unsigned' => true,
          'notnull' => true,
          'length' => 4,
        ),
      'post_id' =>
        array(
          'type' => 'integer',
          'unsigned' => true,
          'notnull' => true,
          'length' => 3,
        ),
      'body' =>
        array(
          'type' => 'string',
          'notnull' => true,
          'length' => NULL,
        ),
      'deleted' =>
        array(
          'type' => 'boolean',
          'notnull' => true,
          'default' => 0,
          'length' => 25,
        ),
      'created_at' =>
        array(
          'type' => 'timestamp',
          'length' => 25,
        ),
      'updated_at' =>
        array(
          'type' => 'timestamp',
          'length' => 25,
        ),
      'lft' =>
        array(
          'type' => 'integer',
          'length' => 4,
        ),
      'rgt' =>
        array(
          'type' => 'integer',
          'length' => 4,
        ),
      'level' =>
        array(
          'type' => 'integer',
          'length' => 2,
        ),
      ), array(
        'indexes' =>
          array(
          ),
        'primary' =>
          array(
            0 => 'id',
          ),
    ));
    $this->createForeignKey('post_comment', array(
      'local' => 'user_id',
      'foreign' => 'id',
      'foreignTable' => 'user',
      'name' => 'post_comment_user_id',
    ));
    $this->createForeignKey('post_comment', array(
      'local' => 'post_id',
      'foreign' => 'id',
      'foreignTable' => 'post',
      'onUpdate' => NULL,
      'onDelete' => 'CASCADE',
      'name' => 'post_comment_post_id',
    ));
	}

	public function down()
	{
    $this->dropForeignKey('post_comment', 'post_comment_user_id');
    $this->dropForeignKey('post_comment', 'post_comment_post_id');
		$this->dropTable('post_comment');
	}
}