<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddPostTheme1Migration extends Doctrine_Migration
{
	public function up()
	{
		$this->createTable('post_theme', array(
      'post_id' =>
        array(
          'type' => 'integer',
          'unsigned' => true,
          'notnull' => true,
          'primary' => true,
          'length' => 3,
        ),
      'theme_id' =>
        array(
          'type' => 'integer',
          'unsigned' => true,
          'notnull' => true,
          'primary' => true,
          'length' => 3,
        ),
    ), array(
      'indexes' =>
        array(
        ),
      'primary' =>
        array(
          0 => 'post_id',
          1 => 'theme_id',
        ),
    ));

    $this->createForeignKey('post_theme', array(
      'local' => 'post_id',
      'foreign' => 'id',
      'foreignTable' => 'post',      
      'onDelete' => 'CASCADE',
      'name' => 'post_theme_post_id',
    ));

    $this->createForeignKey('post_theme', array(
      'local' => 'theme_id',
      'foreign' => 'id',
      'foreignTable' => 'theme',
      'name' => 'post_theme_theme_id',
    ));
	}

	public function down()
	{
    $this->dropForeignKey('post_theme', 'post_theme_post_id');
    $this->dropForeignKey('post_theme', 'post_theme_theme_id');
		$this->dropTable('post_theme');
	}
}