<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddQuestionnaireAnswersMigration extends Doctrine_Migration
{
	public function up()
	{
		$this->createTable('questionnaire_answers', array(
      'id' =>
        array(
          'type' => 'integer',
          'unsigned' => true,
          'primary' => true,
          'autoincrement' => true,
          'length' => 3,
        ),
      'post_id' =>
        array(
          'type' => 'integer',
          'unsigned' => true,
          'notnull' => true,
          'length' => 3,
        ),
      'title' =>
        array(
          'type' => 'string',
          'fixed' => 1,
          'unique' => true,
          'notnull' => true,
          'length' => 200,
        ),
      'vote' =>
        array(
          'type' => 'integer',
          'unsigned' => true,
          'notnull' => true,
          'default' => 0,
          'length' => 2,
        ),
      ), array(
        'indexes' =>
          array(
            'title_index' =>
            array(
              'fields' =>
              array(
                0 => 'title',
              ),
            ),
          ),
        'primary' =>
          array(
           0 => 'id',
          ),
    ));

    $this->createForeignKey('questionnaire_answers', array(
      'local' => 'post_id',
      'foreign' => 'id',
      'foreignTable' => 'post',
      'onUpdate' => NULL,
      'onDelete' => 'CASCADE',
      'name' => 'questionnaire_answers_post_id',
    ));
	}

	public function down()
	{
    $this->dropForeignKey('questionnaire_answers', 'questionnaire_answers_post_id');
		$this->dropTable('questionnaire_answers');
	}
}