<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddReadPostCommentMigration extends Doctrine_Migration
{
	public function up()
	{
		$this->createTable('read_post_comment', array(
      'user_id' =>
        array(
          'type' => 'integer',
          'unsigned' => true,
          'primary' => true,
          'length' => 4,
        ),
      'post_id' =>
        array(
          'type' => 'integer',
          'unsigned' => true,
          'primary' => true,
          'length' => 3,
        ),
      'post_comment_id' =>
        array(
          'type' => 'integer',
          'unsigned' => true,
          'primary' => true,
          'length' => 3,
        ),
      ), array(
      'indexes' =>
        array(
        ),
      'primary' =>
        array(
          0 => 'user_id',
          1 => 'post_id',
          2 => 'post_comment_id',
        ),
    ));

    $this->createForeignKey('read_post_comment', array(
      'local' => 'post_id',
      'foreign' => 'id',
      'foreignTable' => 'post',
      'onUpdate' => NULL,
      'onDelete' => 'CASCADE',
      'name' => 'read_post_comment_post_id',
    ));
    $this->createForeignKey('read_post_comment', array(
      'local' => 'user_id',
      'foreign' => 'id',
      'foreignTable' => 'user',
      'name' => 'read_post_comment_user_id',
    ));
    $this->createForeignKey('read_post_comment', array(
      'local' => 'post_comment_id',
      'foreign' => 'id',
      'foreignTable' => 'post_comment',
      'onUpdate' => NULL,
      'onDelete' => 'CASCADE',
      'name' => 'read_post_comment_post_comment_id',
    ));
	}

	public function down()
	{
    $this->dropForeignKey('read_post_comment', 'read_post_comment_user_id');
    $this->dropForeignKey('read_post_comment', 'read_post_comment_post_id');
    $this->dropForeignKey('read_post_comment', 'read_post_comment_post_comment_id');
		$this->dropTable('read_post_comment');
	}
}