<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddModeratorFiltersMigration extends Doctrine_Migration
{
	public function up()
	{
		$this->createTable('moderator_filters', array(
      'id' =>
        array(
          'type' => 'integer',
          'unsigned' => true,
          'primary' => true,
          'autoincrement' => true,
          'length' => 3,
        ),
      'user_id' =>
        array(
          'type' => 'integer',
          'unsigned' => true,
          'notnull' => true,
          'length' => 4,
        ),
      'name' =>
        array(
          'type' => 'string',
          'notnull' => true,
          'length' => 50,
        ),
      'params' =>
        array(
          'type' => 'array',
          'length' => NULL,
        ),
      ), array(
      'indexes' =>
        array(
        'filter' =>
          array(
            'fields' =>
              array(
                0 => 'user_id',
                1 => 'name',
              ),
            'type' => 'unique',
          ),
        ),
        'primary' =>
          array(
            0 => 'id',
          ),
    ));

    $this->createForeignKey('moderator_filters', array(
      'local' => 'user_id',
      'foreign' => 'id',
      'foreignTable' => 'user',
      'onUpdate' => NULL,
      'onDelete' => 'CASCADE',
      'name' => 'moderator_filters_user_id',
    ));
	}

	public function down()
	{
    $this->dropForeignKey('moderator_filters', 'moderator_filters_user_id');
		$this->dropTable('moderator_filters');
	}
}