<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddBlog2Migration extends Doctrine_Migration
{
	public function up()
	{
//    $this->removeColumn('blog', 'url');
		$this->addColumn('blog', 'deleted', 'boolean', array(
        'default' => 0,
        'notnull' => true,
        'length' => 1,
    ));
    echo "Add 'deleted' column SUCCESS...\r\n";
    
//    $this->addColumn('blog', 'slug', 'string', array('length' => 255));
//    echo "Add 'slug' column SUCCESS...\r\n";

//    $this->addIndex('blog', 'sluggable', array(
//        'fields' =>
//          array(
//            0 => 'slug',
//          ),
//        'type' => 'unique',
//    ));
//    echo "Add index 'sluggable' SUCCESS...\r\n";

//    $this->dropForeignKey('blog', 'blog_author_id');
	}

	public function down()
	{    
//    $this->removeIndex('blog', 'sluggable');
//    $this->removeColumn('blog', 'slug');
		$this->removeColumn('blog', 'deleted');
	}
}