<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddBlog3Migration extends Doctrine_Migration
{
	public function up()
	{		
    $this->createForeignKey('blog', array(
      'local' => 'author_id',
      'foreign' => 'id',
      'foreignTable' => 'blog_author',
      'onUpdate' => NULL,
      'onDelete' => 'CASCADE',
      'name' => 'blog_author_id',
    ));
    echo "Create foreign key 'blog_author_id' SUCCESS...\r\n";
	}

	public function down()
	{
    $this->dropForeignKey('blog', 'blog_author_id');
	}
}