<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlterPostTable1Migration extends Doctrine_Migration
{
	public function up()
	{
    $this->dropForeignKey('post', 'post_blog_id');    
    $this->dropForeignKey('post', 'post_author_id');
    echo "All Keys Droped SUCCESS...\r\n";
    sleep(3);
    $this->removeColumn('post', 'blog_id');
    $this->changeColumn('post', 'author_id', 'integer', array(
      'unsigned' => true,      
      'length' => 3,
    ));
    $this->changeColumn('post', 'post_type', 'enum', array(
      'values' =>
        array(
          0 => 'author_article',
          1 => 'expert_article',
          2 => 'news',
          3 => 'events',
          4 => 'article',
          5 => 'analytics',
          6 => 'answer',
          7 => 'questionnaire',
        ),
      'notnull' => true,
      'length' => NULL,
    ));
    echo "All columns change SUCCESS...\r\n";
    sleep(3);
    $this->createForeignKey('post', array(
      'local' => 'author_id',
      'foreign' => 'id',
      'foreignTable' => 'post_author',
      'onUpdate' => NULL,
      'onDelete' => 'CASCADE',
      'name' => 'post_author_id',
    ));
    echo "Foreign Key create SUCCESS...\r\n";
	}

	public function down()
	{}
}