<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlterPostTable2Migration extends Doctrine_Migration
{
	public function up()
	{
    echo "Add column user_id" . PHP_EOL;
    $this->addColumn('post', 'user_id', 'integer', array(
      'unsigned' => true,
      'length' => 4,
    ));
    echo "Change column post_type" . PHP_EOL;
    $this->changeColumn('post', 'post_type', 'enum', array(
      'values' =>
        array(
          0 => 'author_article',
          1 => 'expert_article',
          2 => 'news',
          3 => 'events',
          4 => 'article',
          5 => 'analytics',
          6 => 'qa',
          7 => 'questionnaire',
        ),
      'notnull' => true,
      'length' => NULL,
    ));
	}

	public function down()
	{
    $this->removeColumn('post', 'user_id');
    echo "Remove column user_id" . PHP_EOL;
    $this->changeColumn('post', 'post_type', 'enum', array(
      'values' =>
        array(
          0 => 'author_article',
          1 => 'expert_article',
          2 => 'news',
          3 => 'events',
          4 => 'article',
          5 => 'analytics',
          6 => 'answer',
          7 => 'questionnaire',
        ),
      'notnull' => true,
      'length' => NULL,
    ));
    echo "Change column post_type" . PHP_EOL;
  }
}