<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlterBlogTable1Migration extends Doctrine_Migration
{
	public function up()
	{
    $this->removeIndex('blog', 'blog_author_id');
    echo "Index blog_auhtor_id removed" . PHP_EOL;
    $this->dropForeignKey('blog', 'blog_author_id');
    echo "Foreign key droped" . PHP_EOL;
    $this->removeColumn('blog', 'author_id');
	}

	public function down()
	{  }
}