<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlterBlogTable2Migration extends Doctrine_Migration
{
	public function up()
	{
    echo "Create Foreign key" . PHP_EOL;
    $this->createForeignKey('blog', array(
      'local' => 'user_id',
      'foreign' => 'id',
      'foreignTable' => 'user',
      'onUpdate' => NULL,
      'onDelete' => 'CASCADE',
      'name' => 'blog_user_id',
    ));
    echo "Foreign key blog_user_id created" . PHP_EOL;
    $this->addIndex('blog', 'blog_user_id', array(
      'fields' =>
        array(
          0 => 'user_id',
        ),
      'type' => 'unique',
    ));
	}

	public function down()
	{  }
}