<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlterBlogTable3Migration extends Doctrine_Migration
{
	public function up()
	{
    $this->addColumn('blog', 'status', 'enum', array(
      'values'  => array(
        0 => 'active',
        1 => 'inactive',
        2 => 'moderate',
        3 => 'restricted'
      ),
      'default' => 'moderate'
    ));
	}

	public function down()
	{
    $this->removeColumn('blog', 'status');
  }
}