<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddPostAuthorEmailColumn063Migration extends Doctrine_Migration
{
	public function up()
	{
    echo "Add column author_email" . PHP_EOL;
    $this->addColumn('post', 'author_email', 'string', array(
      'length' => '60',
      'notnull' => false,
      'default' => null
     ));
	}

	public function down()
	{
    $this->removeColumn('post', 'author_email');
    echo "Remove column author_email" . PHP_EOL;
	}
}