<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddPostEventInfoColumns064Migration extends Doctrine_Migration
{
	public function up()
	{
    echo "Add column event_date" . PHP_EOL;
    $this->addColumn('post', 'event_date', 'string', array(
      'length' => '255',
      'notnull' => false,
      'default' => null
     ));
    
    echo "Add column event_place" . PHP_EOL;
    $this->addColumn('post', 'event_place', 'string', array(
      'length' => '255',
      'notnull' => false,
      'default' => null
     ));

    echo "Add column event_contact" . PHP_EOL;
    $this->addColumn('post', 'event_contact', 'string', array(
      'length' => '255',
      'notnull' => false,
      'default' => null
     ));
	}

	public function down()
	{
    $this->removeColumn('post', 'event_date');
    echo "Remove column author_email" . PHP_EOL;

    $this->removeColumn('post', 'event_place');
    echo "Remove column author_email" . PHP_EOL;

    $this->removeColumn('post', 'event_contact');
    echo "Remove column author_email" . PHP_EOL;
	}
}