<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddKeyUserRegion066Migration extends Doctrine_Migration
{
	public function up()
	{
		$this->createForeignKey('user_region', array(
      'local' => 'region_id',
      'foreign' => 'id',
      'foreignTable' => 'region',
      'onUpdate' => NULL,
      'onDelete' => 'cascade',
      'name' => 'user_region_region_id',
    ));
    $this->createForeignKey('user_region', array(
      'local' => 'user_id',
      'foreign' => 'id',
      'foreignTable' => 'user',
      'onUpdate' => NULL,
      'onDelete' => 'cascade',
      'name' => 'user_region_user_id',
    ));
	}

	public function down()
	{
		$this->dropForeignKey('user_region', 'user_region_region_id');
		$this->dropForeignKey('user_region', 'user_region_user_id');
	}
}