<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlterQuestionnaire069Migration extends Doctrine_Migration
{
	public function up()
	{
    $this->dropForeignKey('questionnaire_answers_vote', 'questionnaire_answers_vote_answer_id');
		$this->dropForeignKey('questionnaire_answers_vote', 'questionnaire_answers_vote_post_id');
		$this->dropForeignKey('questionnaire_answers_vote', 'questionnaire_answers_vote_user_id');
    
    $this->removeIndex('questionnaire_answers_vote', 'uservote');
	}

	public function down()
	{
    $this->createForeignKey('questionnaire_answers_vote', array(
      'local' => 'answer_id',
      'foreign' => 'id',
      'foreignTable' => 'questionnaire_answers',
      'onUpdate' => NULL,
      'onDelete' => 'CASCADE',
      'name' => 'questionnaire_answers_vote_answer_id',
    ));
    $this->createForeignKey('questionnaire_answers_vote', array(
      'local' => 'post_id',
      'foreign' => 'id',
      'foreignTable' => 'post',
      'onUpdate' => NULL,
      'onDelete' => 'CASCADE',
      'name' => 'questionnaire_answers_vote_post_id',
    ));
    $this->createForeignKey('questionnaire_answers_vote', array(
      'local' => 'user_id',
      'foreign' => 'id',
      'foreignTable' => 'user',
      'name' => 'questionnaire_answers_vote_user_id',
    ));

    $this->addIndex('questionnaire_answers_vote', 'uservote', array(
      'fields' => array(
        'post_id' => array(
          'unique' => true
        ),
        'user_id' => array(
          'unique' => true
        )
      )
    ));
	}
}