<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlterQuestionnaireAnswersVote070Migration extends Doctrine_Migration
{
	public function up()
	{
    $this->createForeignKey('questionnaire_answers_vote', array(
      'local' => 'answer_id',
      'foreign' => 'id',
      'foreignTable' => 'questionnaire_answers',
      'onUpdate' => NULL,
      'onDelete' => 'cascade',
      'name' => 'questionnaire_answers_vote_answer_id',
    ));
    $this->createForeignKey('questionnaire_answers_vote', array(
      'local' => 'post_id',
      'foreign' => 'id',
      'foreignTable' => 'post',
      'onUpdate' => NULL,
      'onDelete' => 'cascade',
      'name' => 'questionnaire_answers_vote_post_id',
    ));
    $this->createForeignKey('questionnaire_answers_vote', array(
      'local' => 'user_id',
      'foreign' => 'id',
      'foreignTable' => 'user',
      'onUpdate' => NULL,
      'onDelete' => 'cascade',
      'name' => 'questionnaire_answers_vote_user_id',
    ));
	}

	public function down()
	{
    $this->dropForeignKey('questionnaire_answers_vote', 'questionnaire_answers_vote_answer_id');
		$this->dropForeignKey('questionnaire_answers_vote', 'questionnaire_answers_vote_post_id');
		$this->dropForeignKey('questionnaire_answers_vote', 'questionnaire_answers_vote_user_id');
	}
}