<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddClaimu072Migration extends Doctrine_Migration
{
	public function up()
	{
		$this->createTable('claim', array(
      'id' =>
        array(
          'type' => 'integer',
          'unsigned' => true,
          'primary' => true,
          'autoincrement' => true,
          'length' => 32,
        ),
      'user_id' =>
        array(
          'type' => 'integer',
          'unsigned' => true,
          'notnull' => true,
          'length' => 4,
        ),
      'lot_id' =>
        array(
          'type' => 'integer',
          'unsigned' => true,
          'notnull' => true,
          'length' => 4,
        ),
      'claim_theme_id' =>
        array(
          'type' => 'integer',
          'unsigned' => true,
          'notnull' => true,
          'length' => 4,
        ),
      'status' =>
      array(
        'type' => 'enum',
        'values' => array(
          0 => 'new',
          1 => 'confirmed',
          2 => 'not_confirmed',
          3 => 'on_control',
          4 => 'need_check',
          5 => 'fixed'
        ),
        'notnull' => true,
        'dafault' => 'new'        
      ),
      'body' =>
        array(
          'type' => 'string',
          'notnull' => true,
          'length' => NULL,
        ),
      'created_at' =>
        array(
          'type' => 'timestamp',
          'length' => 25,
        ),
      'updated_at' =>
        array(
          'type' => 'timestamp',
          'length' => 25,
        )
    ));

    $this->createForeignKey('claim', array(
      'local' => 'user_id',
      'foreign' => 'id',
      'foreignTable' => 'user',
      'name' => 'claim_user_id',
    ));
    $this->createForeignKey('claim', array(
      'local' => 'lot_id',
      'foreign' => 'id',
      'foreignTable' => 'lot',
      'onUpdate' => NULL,
      'onDelete' => 'CASCADE',
      'name' => 'claim_lot_id',
    ));
    $this->createForeignKey('claim', array(
      'local' => 'claim_theme_id',
      'foreign' => 'id',
      'foreignTable' => 'claim_theme',
      'onUpdate' => NULL,
      'onDelete' => 'CASCADE',
      'name' => 'claim_claim_theme_id',
    ));
	}

	public function down()
	{
    $this->dropForeignKey('claim', 'claim_user_id');
    $this->dropForeignKey('claim', 'claim_lot_id');
    $this->dropForeignKey('claim', 'claim_claim_theme_id');
    $this->dropTable('claim');
	}
}