<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlterBlogPost073Migration extends Doctrine_Migration
{
	public function up()
	{
    $this->dropForeignKey('blog_post_theme', 'blog_post_theme_post_id');
    $this->dropForeignKey('blog_post_theme', 'blog_post_theme_theme_id');
    $this->dropTable('blog_post_theme');

    $this->addColumn('blog_post', 'theme_id', 'integer', array(
      'length' => 3,
      'unsigned' => true
    ));


  }

	public function down()
	{
    
    $this->removeColumn('blog_post', 'theme_id');
		$this->createTable('blog_post_theme', array(
      'post_id' =>
        array(
          'type' => 'integer',
          'unsigned' => true,
          'primary' => true,
          'length' => 4,
        ),
      'theme_id' =>
        array(
          'type' => 'integer',
          'unsigned' => true,
          'primary' => true,
          'length' => 3,
        ),
      ), array(
        'indexes' =>
          array(
          ),
        'primary' =>
          array(
            0 => 'post_id',
            1 => 'theme_id',
          ),
    ));

    $this->createForeignKey('blog_post_theme', array(
      'local' => 'post_id',
      'foreign' => 'id',
      'foreignTable' => 'blog_post',
      'onUpdate' => NULL,
      'onDelete' => 'CASCADE',
      'name' => 'blog_post_theme_post_id',
    ));
    $this->createForeignKey('blog_post_theme', array(
      'local' => 'theme_id',
      'foreign' => 'id',
      'foreignTable' => 'theme',
      'onUpdate' => NULL,
      'onDelete' => 'CASCADE',
      'name' => 'blog_post_theme_theme_id',
    ));
	}
}