<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlterBlogPost074Migration extends Doctrine_Migration
{
	public function up()
	{
    $this->createForeignKey('blog_post', array(
      'local' => 'theme_id',
      'foreign' => 'id',
      'foreignTable' => 'theme',
      'onUpdate' => NULL,
      'onDelete' => 'CASCADE',
      'name' => 'blog_post_theme_id',
    ));
	}

	public function down()
	{
    $this->dropForeignKey('blog_post', 'blog_post_theme_id');
	}
}