<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddPostComment076Migration extends Doctrine_Migration
{
	public function up()
	{
		$this->changeColumn('post_comment', 'user_id', 'integer', array(
      'unsigned' => true,
      'length' => 4
    ));
    $this->addColumn('post_comment', 'user_name', 'string', array(
      'length' => 50,
    ));
    $this->addColumn('post_comment', 'user_email', 'string', array(
      'length' => 60,
    ));
	}

	public function down()
	{
    $this->changeColumn('post_comment', 'user_id', 'integer', array(
      'unsigned' => true,
      'length' => 4,
      'notnull' => true
    ));
		$this->removeColumn('post_comment', 'user_name');
	}
}