<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddLotView077Migration extends Doctrine_Migration
{
	public function up()
	{
		$this->createTable('lot_view', array(
      'id' =>
        array(
          'type' => 'integer',
          'unsigned' => true,
          'primary' => true,
          'autoincrement' => true,
          'length' => 40,
        ),
      'lot_id' =>
        array(
          'type' => 'integer',
          'unsigned' => true,
          'notnull' => true,
          'length' => 4,
        ),
      'ip_address' =>
        array(
          'type' => 'string',
          'length' => 15,
          'notnull' => true,
        ),
      'created_at' =>
        array(
          'type' => 'timestamp',
          'length' => 25,
        )
      ), array(
        'primary' =>
          array(
            0 => 'id',
          ),
    ));

    $this->createForeignKey('lot_view', array(
      'local' => 'lot_id',
      'foreign' => 'id',
      'foreignTable' => 'lot',
      'onUpdate' => NULL,
      'onDelete' => 'CASCADE',
      'name' => 'lot_view_lot_id',
    ));
	}

	public function down()
	{
    $this->dropForeignKey('lot_view', 'lot_view_lot_id');
		$this->dropTable('lot_view');
	}
}