<?php
/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class AddPromotionMigration extends Doctrine_Migration
{
  public function up()
  {
    $this->addColumn('user_info', 'promotion', 'integer', array('length' => 2, 'default' => 0));
  }

  public function down()
  {
    $this->removeColumn('user_info', 'promotion');
  }
}