<?php
/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class AddXmlFormFieldMigration extends Doctrine_Migration
{
  public function up()
  {
    $this->addColumn('form_field', 'xml_name', 'string', array('length' => 255, 'default' => null));
    $this->addColumn('form_field', 'xml_desc', 'string', array('length' => 1000, 'default' => null));
  }

  public function down()
  {
    $this->removeColumn('form_field', 'xml_name');
    $this->removeColumn('form_field', 'xml_desc');
  }
}