<?php
/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class AddXmlUserInfoMigration extends Doctrine_Migration
{
  public function up()
  {
    $this->addColumn('user_info', 'xml_url', 'string', array('length' => 255, 'default' => null));
    $this->addColumn('user_info', 'xml_type', 'enum', array(
      'notnull'  => true,
      'values'   => array('mesto', 'gde', 'irr', 'mail', 'winner', 'mir', 'dmir'),
      'default'  => 'mesto',
    ));
  }

  public function down()
  {
    $this->removeColumn('user_info', 'xml_url');
    $this->removeColumn('user_info', 'xml_type');
  }
}