<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlterLot084Migration extends Doctrine_Migration
{
	public function up()
	{    
    $this->addColumn('lot', 'updated_at', 'timestamp', array(
      'length'  => 25,
     ));
	}

	public function down()
	{
    $this->removeColumn('lot', 'updated_at');
	}
}