<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddForeignKeySource086Migration extends Doctrine_Migration
{
	public function up()
	{
		$this->createForeignKey('user_sources_link', array(
      'local' => 'user_id',
      'foreign' => 'id',
      'foreignTable' => 'user',
      'onUpdate' => NULL,
      'onDelete' => 'cascade',
      'name' => 'user_sources_link_user_id',
    ));
	}

	public function down()
	{		
		$this->dropForeignKey('user_sources_link', 'user_sources_link_user_id');
	}
}