<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlterLotOrgLength extends Doctrine_Migration
{
	public function up()
	{
    $this->changeColumn('lot', 'organization_contact_name', 'string', array('length' => 150));
	}

	public function down()
	{
    $this->changeColumn('lot', 'organization_contact_name', 'string', array('length' => 50));
	}
}