<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddImportErrorsLog090Migration extends Doctrine_Migration
{
	public function up()
	{
		$this->createTable('import_errors_log', array(
      'id' =>
        array(
          'type' => 'integer',
          'length' => 20,
          'autoincrement' => true,
          'primary' => true,
        ),
      'log_id' =>
        array(
          'type' => 'integer',
          'unsigned' => true,
          'notnull' => true,
          'length' => 4,
        ),
      'internal_lot_id' =>
        array(
          'type' => 'integer',
          'unsigned' => true,
          'length' => 4,
        ),
      ), array(
        'indexes' =>
          array(
          ),
        'primary' =>
          array(
            0 => 'id',
          ),
      )
    );

    $this->addIndex('import_errors_log', 'log_id', array(
      'fields' => array(
        'log_id'
      )
    ));
	}

	public function down()
	{
		$this->dropTable('import_errors_log');
	}
}