<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddImportTypesLog091Migration extends Doctrine_Migration
{
	public function up()
	{
		$this->createTable('import_types_log', array(
      'id' =>
        array(
          'type' => 'integer',
          'length' => 20,
          'autoincrement' => true,
          'primary' => true,
        ),
      'log_id' =>
        array(
          'type' => 'integer',
          'unsigned' => true,
          'notnull' => true,
          'length' => 4,
        ),
      'type' =>
        array(
          'type' => 'integer',
          'unsigned' => true,
          'notnull' => true,
          'length' => 1,
        ),
      'lots' =>
        array(
          'type' => 'integer',
          'unsigned' => true,
          'notnull' => true,
          'length' => 1,
        ),
      ), array(
        'indexes' =>
          array(
          ),
        'primary' =>
          array(
            0 => 'id',
          ),
      )
    );

    $this->addIndex('import_types_log', 'type', array(
      'fields' => array(
        'type'
      )
    ));
	}

	public function down()
	{
		$this->dropTable('import_types_log');
	}
}