<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddFksImport092Migration extends Doctrine_Migration
{
	public function up()
	{
		$this->createForeignKey('import_errors_log', array(
      'local' => 'log_id',
      'foreign' => 'id',
      'foreignTable' => 'import_log',
      'onUpdate' => NULL,
      'onDelete' => 'cascade',
      'name' => 'import_errors_log_log_id',
    ));
    $this->createForeignKey('import_log', array(
      'local' => 'user_id',
      'foreign' => 'id',
      'foreignTable' => 'user',
      'onUpdate' => NULL,
      'onDelete' => 'cascade',
      'name' => 'import_log_user_id',
    ));
    $this->createForeignKey('import_regions_log', array(
      'local' => 'log_id',
      'foreign' => 'id',
      'foreignTable' => 'import_log',
      'onUpdate' => NULL,
      'onDelete' => 'cascade',
      'name' => 'import_regions_log_log_id',
    ));
    $this->createForeignKey('import_regions_log', array(
      'local' => 'region_id',
      'foreign' => 'id',
      'foreignTable' => 'region',
      'onUpdate' => NULL,
      'onDelete' => 'cascade',
      'name' => 'import_regions_log_region_id',
    ));
    $this->createForeignKey('import_types_log', array(
      'local' => 'log_id',
      'foreign' => 'id',
      'foreignTable' => 'import_log',
      'onUpdate' => NULL,
      'onDelete' => 'cascade',
      'name' => 'import_types_log_log_id',
    ));
	}

	public function down()
	{		
		$this->dropForeignKey('import_errors_log', 'import_errors_log_log_id');
		$this->dropForeignKey('import_log', 'import_log_user_id');
		$this->dropForeignKey('import_regions_log', 'import_regions_log_log_id');
		$this->dropForeignKey('import_regions_log', 'import_regions_log_region_id');
		$this->dropForeignKey('import_types_log', 'import_types_log_log_id');
	}
}