<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addseotexts extends Doctrine_Migration
{
	public function up()
	{
		$this->createTable('seo_texts', array(
      'id' =>
        array(
          'type' => 'integer',
          'unsigned' => true,
          'notnull' => true,
          'length' => 4,
          'primary' => true,
          'autoincrement' =>  true
        ),
      'region_id' =>
        array(
          'type' => 'integer',
          'unsigned' => true,
          'notnull' => true,
          'length' => 1,
        ),
      'region_node_id' =>
        array(
          'type' => 'integer',
          'unsigned' => true,
          'length' => 3,
        ),
      'section' =>
        array(
          'type' => 'integer',
          'unsigned' => true,
          'notnull' => true,
          'length' => 1,
        ),
      'real_estate_type' =>
        array(
          'type' => 'string',
          'length' => 35,
        ),
      'text' =>
        array(
          'type' => 'string',
          'length' => 5000,
        ),
      ), array(
        'indexes' =>
          array(
          ),
        'primary' =>
          array(
          ),
    ));

    $this->addIndex('seo_texts', 'section', array(
      'fields'  =>  array('section' => array())
    ));
	}

	public function down()
	{
    $this->dropTable('seo_texts');
	}
}