<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddForeignkeyconstraintsSeotexts095Migration extends Doctrine_Migration
{
	public function up()
	{
		$this->createForeignKey('seo_texts', array(
      'local' => 'region_id',
      'foreign' => 'id',
      'foreignTable' => 'region',
      'onUpdate' => NULL,
      'onDelete' => 'cascade',
      'name' => 'seo_texts_region_id',
    ));
    $this->createForeignKey('seo_texts', array(
      'local' => 'region_node_id',
      'foreign' => 'id',
      'foreignTable' => 'regionnode',
      'onUpdate' => NULL,
      'onDelete' => 'cascade',
      'name' => 'seo_texts_region_node_id',
    ));
	}

	public function down()
	{		
    $this->dropForeignKey('seo_texts', 'seo_texts_region_id');
    $this->dropForeignKey('seo_texts', 'seo_texts_region_node_id');
	}
}