<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddToForm098Migration extends Doctrine_Migration
{
	public function up()
	{
    $form_field = new FormField();
    $form_field->type   = 'select';
    $form_field->value  = "сутки\nмесяц";
    $form_field->label  = 'Вид аренды';
    $form_field->xml_name = 'currency-type';
    $form_field->xml_desc = 'Вид аренды';
    $form_field->save();

    $form = new Form();
    $form->type     = 'apartament-rent';
    $form->field_id = $form_field->id;
    $form->position = 4;
    $form->required = true;
    $form->save();
    
    $form_field->free();
    unset($form_field);

    $form_field = new FormField();
    $form_field->type   = 'select';
    $form_field->value  = "месяц\nгод";
    $form_field->xml_name = 'currency-type';
    $form_field->xml_desc = 'Вид аренды';
    $form_field->save();

    $form = new Form();
    $form->type     = 'commercial-rent';
    $form->field_id = $form_field->id;
    $form->position = 4;
    $form->required = true;
    $form->save();

    $form_field->free();
    unset($form_field);
	}

	public function down()
	{ }
}