<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddXmlNamesFormField100Migration extends Doctrine_Migration
{
	public function up()
	{
    $fields = array(
      1   =>  'full-area',
      2   =>  'full-price',
      3   =>  'floor',
      4   =>  'floors-total',
      5   =>  'build-year',
      6   =>  'house-type',
      7   =>  'floor-space',
      8   =>  'kitchen-area',
      9   =>  'ceilings-height',
      10  =>  'rooms-arrangement',
      11  =>  'sewerage',
      12  =>  'windows',
      13  =>  'flooring',
      14  =>  'quality',
      15  =>  'balcony',
      20  =>  'details',
      54  =>  'offer-type',
      1   =>  'full-area',
      3   =>  'floor',
      4   =>  'floors-total',
      5   =>  'build-year',
      6   =>  'house-type',
      7   =>  'floor-space',
      8   =>  'kitchen-area',
      9   =>  'ceilings-height',
      10  =>  'rooms-arrangement',
      11  =>  'sewerage',
      12  =>  'windows',
      15  =>  'balcony',
      16  =>  'price',
      17  =>  'quality',
      18  =>  'furniture',
      19  =>  'equipment',
      21  =>  'details',
      55  =>  'offer-type',
      66  =>  'agent-fee',
      68  =>  'currency-type',
      4   =>  'floors-total',
      5   =>  'build-year',
      16  =>  'price',
      18  =>  'furniture',
      19  =>  'equipment',
      23  =>  'details',
      26  =>  'lot-area',
      27  =>  'area',
      28  =>  'house-type',
      35  =>  'rooms-count',
      36  =>  'city-distance',
      37  =>  'city-type',
      43  =>  'land-type',
      44  =>  'additional-structures',
      56  =>  'gas',
      57  =>  'electricity',
      58  =>  'waterpipe',
      59  =>  'sewerage',
      60  =>  'heating',
      61  =>  'quality',
      2   =>  'full-price',
      4   =>  'floors-total',
      5   =>  'build-year',
      22  =>  'details',
      26  =>  'lot-area',
      27  =>  'area',
      28  =>  'house-type',
      29  =>  'quality',
      30  =>  'heating',
      31  =>  'gas',
      32  =>  'electricity',
      33  =>  'waterpipe',
      34  =>  'sewerage',
      35  =>  'rooms-count',
      36  =>  'city-distance',
      37  =>  'city-type',
      38  =>  'groundwork',
      39  =>  'walls',
      40  =>  'facade',
      41  =>  'flooring',
      42  =>  'furniture',
      43  =>  'land-type',
      44  =>  'additional-structures',
      64  =>  'offer-type',
      67  =>  'land-designation',
      45  =>  'commercial-type',
      46  =>  'full-floor-area',
      47  =>  'full-earth-area',
      48  =>  'earth-type',
      49  =>  'building-type',
      50  =>  'office-class',
      51  =>  'quality',
      24  =>  'details',
      25  =>  'details',
      52  =>  'layout-type',
      53  =>  'price',
      63  =>  'quality',
      69  =>  'currency-type'
    );

    $form_fields = Doctrine::getTable('FormField')
      ->createQuery()            
      ->execute();
    
    foreach ($form_fields as $ff) {
      if (!empty($fields[$ff->id])) {
        $ff->xml_name = $fields[$ff->id];
        $ff->save();
        $ff->free();
      }
    }
	}

	public function down()
	{
    $form_fields = Doctrine::getTable('FormField')
      ->createQuery()
      ->execute();
    
    foreach ($form_fields as $ff) {
      $ff->xml_name = null;
      $ff->save();
      $ff->free();
    }
  }
}