<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddLotsStatistic102Migration extends Doctrine_Migration
{
	public function up()
	{
		$this->createTable('lot_statistic', array(
      'id' => 
        array(
          'type' => 'integer',
          'unsigned' => true,
          'primary' => true,
          'autoincrement' => true,
          'length' => 4,
        ),
      'stat_at' => 
        array(
          'type' => 'date',
          'notnull' => true,
          'length' => 10,
        ),
      'region_id' => 
        array(
          'type' => 'integer',
          'unsigned' => true,
          'notnull' => true,
          'length' => 1,
        ),
      'type' => 
        array(
          'type' => 'enum',
          'values' => 
            array(
              0 => 'new_building-sale',
              1 => 'apartament-sale',
              2 => 'apartament-rent',
              3 => 'house-sale',
              4 => 'house-rent',
              5 => 'commercial-sale',
              6 => 'commercial-rent',
            ),
          'length' => NULL,
       ),
      'user_type' => 
        array(
          'type' => 'enum',
          'values' => 
            array(
              0 => 'owner',
              1 => 'company',
              2 => 'employee',
              3 => 'realtor',
              4 => 'source',
            ),
          'notnull' => true,
          'length' => NULL,
        ),
      'active' => 
        array(
          'type' => 'integer',
          'notnull' => true,
          'default' => 0,
          'length' => 2,
        ),
      'new' => 
        array(
          'type' => 'integer',
          'notnull' => true,
          'default' => 0,
          'length' => 2,
        ),
      'deleted' => 
        array(
          'type' => 'integer',
          'notnull' => true,
          'default' => 0,
          'length' => 2,
        ),
      ), array(
        'indexes' => 
          array(
            'stat_at' => 
              array(
                'fields' => 
                  array(
                    0 => 'stat_at',
                  ),
              ),
          'region_id' => 
            array(
              'fields' => 
                array(
                  0 => 'region_id',
                ),
            ),
          'type' => 
            array(
              'fields' => 
                array(
                  0 => 'type',
                ),
            ),
          'user_type' => 
            array(
              'fields' => 
                array(
                  0 => 'user_type',
                ),
            ),
        ),
        'primary' => 
          array(
            0 => 'id',
          ),
    ));
	}

	public function down()
	{
		$this->dropTable('lot_statistic');
	}
}