<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApplyForeignKeyConstraintsLotStatistic103Migration extends Doctrine_Migration
{
	public function up()
	{
		$this->createForeignKey('lot_statistic', array(
      'local' => 'region_id',
      'foreign' => 'id',
      'foreignTable' => 'region',
      'onUpdate' => NULL,
      'onDelete' => 'cascade',
      'name' => 'lot_statistic_region_id',
    ));
	}

	public function down()
	{		
		$this->dropForeignKey('lot_statistic', 'lot_statistic_region_id');
	}
}