<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddLotsStatisticIndex104Migration extends Doctrine_Migration
{
	public function up()
	{
		$this->addIndex('lot_statistic', 'unique_data', array(
      'fields' =>
        array(
          0 => 'stat_at',
          1 => 'region_id',
          2 => 'type',
          3 => 'user_type'
        ),
      'type' => 'unique',  
    ));
	}

	public function down()
	{
		$this->removeIndex('lost_statistic', 'unique_data');
	}
}