<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddSphCounter105Migration extends Doctrine_Migration
{
	public function up()
	{
		$this->createTable('sph_counter', array(
      'id' => 
        array(
          'type' => 'integer',
          'unsigned' => true,
          'primary' => true,
          'length' => 1,
        ),
      'last_updated_at' => 
        array(
          'type' => 'timestamp',
          'length' => 25,
        ),
      ), array(
        'indexes' => 
          array(
            'last_updated_at' => 
              array(
                'fields' => 
                  array(
                    0 => 'last_updated_at',
                  ),
              ),
          ),
      'primary' => 
        array(
          0 => 'id',
        ),
    ));
	}

	public function down()
	{
		$this->dropTable('sph_counter');
	}
}