<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddFormFieldsNb107Migration extends Doctrine_Migration
{
  public function up()
  {
    $form_field = new FormField();
    $form_field->type   = 'price';
    $form_field->label  = 'Мин. цена кв.м.';
    $form_field->comment = 'Мин. цена кв.м. (новостройки)';
    $form_field->xml_name = 'min-price';
    $form_field->xml_desc = 'Минимальная цена';
    $form_field->rating = 3;
    $form_field->save();

    $form = new Form();
    $form->type     = 'new_building-sale';
    $form->field_id = $form_field->id;
    $form->position = 1;
    $form->required = true;
    $form->save();
    
    $form_field->free();
    unset($form_field);
    //=================================================
    $form_field = new FormField();
    $form_field->type   = 'price';
    $form_field->label  = 'Макс. цена кв.м';
    $form_field->comment = 'Макс. цена кв.м (новостройки)';
    $form_field->xml_name = 'max-price';
    $form_field->xml_desc = 'Максимальная цена';
    $form_field->rating = 3;
    $form_field->save();

    $form = new Form();
    $form->type     = 'new_building-sale';
    $form->field_id = $form_field->id;
    $form->position = 2;
    $form->required = true;
    $form->save();
    
    $form_field->free();
    unset($form_field);
    //=================================================
    $form_field = new FormField();
    $form_field->type   = 'integer';
    $form_field->label  = 'Мин. площадь';
    $form_field->help = 'кв.м.';
    $form_field->comment = 'Мин. площадь (новостройки)';
    $form_field->xml_name = 'min-area';
    $form_field->xml_desc = 'Минимальная площадь';
    $form_field->rating = 1;
    $form_field->save();

    $form = new Form();
    $form->type     = 'new_building-sale';
    $form->field_id = $form_field->id;
    $form->position = 3;
    $form->required = true;
    $form->save();
    
    $form_field->free();
    unset($form_field);
    //=================================================
    $form_field = new FormField();
    $form_field->type   = 'integer';
    $form_field->label  = 'Макс. площадь';
    $form_field->help = 'кв.м.';
    $form_field->comment = 'Макс. площадь (новостройки)';
    $form_field->xml_name = 'max-area';
    $form_field->xml_desc = 'Максимальная площадь';
    $form_field->rating = 1;
    $form_field->save();

    $form = new Form();
    $form->type     = 'new_building-sale';
    $form->field_id = $form_field->id;
    $form->position = 4;
    $form->required = true;
    $form->save();
    
    $form_field->free();
    unset($form_field);
    //=================================================
    $form = new Form();
    $form->type     = 'new_building-sale';
    $form->field_id = 4;
    $form->position = 5;
    $form->required = true;
    $form->save();
    //=================================================
    $form_field = new FormField();
    $form_field->type   = 'select';
    $form_field->value = "проект\nкотлован\nстроится\nпостроен\nсдан";
    $form_field->label  = 'Состояние строительства';
    $form_field->comment = 'Состояние строительства (новостройки)';
    $form_field->xml_name = 'building-state';
    $form_field->xml_desc = 'Состояние строительства';
    $form_field->rating = 1;
    $form_field->save();

    $form = new Form();
    $form->type     = 'new_building-sale';
    $form->field_id = $form_field->id;
    $form->position = 7;
    $form->required = true;
    $form->save();
    
    $form_field->free();
    unset($form_field);
    //=================================================
    $form_field = new FormField();
    $form_field->type   = 'float';
    $form_field->label  = 'Удаленность от метро/ж.д. станции';
    $form_field->help = 'м.';
    $form_field->xml_name = 'transport-distance';
    $form_field->xml_desc = 'Удаленность от метро/ж.д. станции';
    $form_field->rating = 1;
    $form_field->save();

    $form = new Form();
    $form->type     = 'new_building-sale';
    $form->field_id = $form_field->id;
    $form->position = 9;
    $form->required = true;
    $form->save();
    
    $form_field->free();
    unset($form_field);
    //=================================================
    $form_field = new FormField();
    $form_field->type   = 'multiple';
    $form_field->value = "1\n2\n3\n4\n5\nсвоб. планировка";
    $form_field->label  = 'Квартиры в доме';
    $form_field->comment = 'Квартиры в доме (новостройки)';
    $form_field->help = 'комнатные';
    $form_field->rating = 5;
    $form_field->xml_name = 'flat-types';
    $form_field->xml_desc = 'Квартиры в доме';
    $form_field->save();

    $form = new Form();
    $form->type     = 'new_building-sale';
    $form->field_id = $form_field->id;
    $form->position = 6;
    $form->required = true;
    $form->save();
    
    $form_field->free();
    unset($form_field);
    //=================================================
    $form = new Form();
    $form->type     = 'new_building-sale';
    $form->field_id = 6;
    $form->position = 8;
    $form->required = true;
    $form->save();
  }

  public function down()
  {
    
  }
}
