<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlterPost110Migration extends Doctrine_Migration
{
	public function up()
	{
		$this->addColumn('post', 'updated_at', 'timestamp', array(        
        'length' => 25
      )
    );
    
    $this->addIndex('post', 'updated_at', array(
      'fields' =>
        array(
          0 => 'updated_at',
        ),      
    ));
    
	}

	public function down()
	{
		$this->removeIndex('post', 'updated_at');
    $this->removeColumn('post', 'updated_at');
	}
}