<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddSphPortalCounter111Migration extends Doctrine_Migration
{
	public function up()
	{
		$this->createTable('sph_portal_counter', array(
      'id' => 
        array(
          'type' => 'integer',
          'unsigned' => true,
          'primary' => true,
          'autoincrement' => true,
          'length' => 1,
        ),
      'type' => 
        array(
          'type' => 'enum',
          'values' => 
            array(
              0 => 'expert_article',
              1 => 'author_article',
              2 => 'news',
              3 => 'events',
              4 => 'article',
              5 => 'analytics',
              6 => 'qa',              
              8 => 'blog',
            ),
          'notnull' => true,
          'length' => NULL,
        ),
      'last_updated_at' => 
        array(
          'type' => 'timestamp',
          'length' => 25          
        ),
      ), array(
        'indexes' => 
          array(
            'last_updated_at' => 
              array(
                'fields' => 
                  array(
                    0 => 'last_updated_at',
                  ),
              ),
            'type' => 
              array(
                'fields' => 
                  array(
                    0 => 'type',
                  ),
              ),
          )
    ));
	}

	public function down()
	{
		$this->dropTable('sph_portal_counter');
	}
}