<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddSphPortalCounterData112Migration extends Doctrine_Migration
{
	public function up()
	{
    $post_types = array(
      'news', 'article', 'analytics', 'events', 'expert_article', 'author_article',
      'qa', 'blog'
    );
		foreach ($post_types as $type) {      
      $post_counter = new SphPortalCounter();
      $post_counter->type = $type;        
      $post_counter->save();
      $post_counter->free();
    }
	}

	public function down()
	{	}
}