<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlterBlogPost113Migration extends Doctrine_Migration
{
	public function up()
	{
    $this->addColumn('blog_post', 'updated_at', 'timestamp',array(
      'length' => 25
    ));
    
    $this->addIndex('blog_post', 'updated_at', array(
      'fields' =>
        array(
          0 => 'updated_at',
        ),
    ));
	}

	public function down()
	{	    
    $this->removeIndex('blog_post', 'updated_at');
    $this->removeColumn('blog_post', 'updated_at');
  }
}