<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlterLot114Migration extends Doctrine_Migration
{
	public function up()
	{
    $this->addColumn('lot', 'parsed_at', 'timestamp',array(
      'length' => 25
    ));
    
    $this->addIndex('lot', 'parsed_at', array(
      'fields' =>
        array(
          0 => 'parsed_at',
        ),
    ));
	}

	public function down()
	{	    
    $this->removeIndex('lot', 'parsed_at');
    $this->removeColumn('lot', 'parsed_at');
  }
}