<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlterBlogPost115Migration extends Doctrine_Migration
{
  public function up()
  {
    $this->addColumn('blog_post', 'title_h1', 'string', 
      array(
        'length' => 255,
      )
    );
    
    $this->addColumn('blog_post', 'description', 'string',
      array(
        'length' => 255,
      )
    );
    
    $this->addColumn('blog_post', 'keywords', 'string', 
      array(
        'length' => 255,
      )
    );
  }

  public function down()
  {
    $this->removeColumn('blog_post', 'title_h1');
    $this->removeColumn('blog_post', 'description');
    $this->removeColumn('blog_post', 'keywords');
  }
}