<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addsitemapseodata extends Doctrine_Migration
{
	public function up()
	{
		$this->createTable('sitemap_seo_data', array(
             'id' => 
             array(
              'type' => 'integer',
              'unsigned' => true,
              'primary' => true,
              'autoincrement' => true,
              'length' => 4,
             ),
             'h1' => 
             array(
              'type' => 'string',
              'length' => 500,
             ),
             'section' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 10,
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => 500,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
	}

	public function down()
	{
		$this->dropTable('sitemap_seo_data');
	}
}