<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlterSitemapSeoData119Migration extends Doctrine_Migration
{
  public function up()
  {
    $this->addColumn('sitemap_seo_data', 'link', 'string', 
      array(
        'length' => 500,
      )
    );
    
  }

  public function down()
  {
    $this->removeColumn('sitemap_seo_data', 'link');
  }
}
