<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlterSitemapSeoData121Migration extends Doctrine_Migration
{
  public function up()
  {
    $this->addColumn('sitemap_seo_data', 'level', 'enum', 
      array(
        'length' => 5,
        'values' => array(
          'region',
          'city',
          'village',
          'district',
          'street'
        ),
      )
    );
    
  }

  public function down()
  {
    $this->removeColumn('sitemap_seo_data', 'level');
  }
}
