<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlterSitemapSeoData123Migration extends Doctrine_Migration
{
  public function up()
  {
    $this->changeColumn('sitemap_seo_data', 'section', 'string', 
      array(
        'length' => 100
      )
    );
    
  }

  public function down()
  {
    $this->changeColumn('sitemap_seo_data', 'section', 'string',
      array(
        'length' => 10
      )
    );
  }
}
