<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlterBlogPost126Migration extends Doctrine_Migration
{
  public function up()
  {
    $this->addColumn('blog_post', 'title_seo', 'string', 
      array(
        'length' => 255,
      )
    );
    
  }

  public function down()
  {
    $this->removeColumn('blog_post', 'title_seo');
  }
}