<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlterPM129Migration extends Doctrine_Migration
{
	public function up()
	{
    $this->addColumn('p_m', 'is_deleted', 'integer', array(
      'unsigned'  => true,
      'length'    => 1,
    ));
	}

	public function down()
	{
		$this->removeColumn('p_m', 'is_deleted');
	}
}