<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlterSitemapSeoData130Migration extends Doctrine_Migration
{
	public function up()
	{
      $this->addColumn('sitemap_seo_data', 'content', 'string', array(
        'length'  => 5000
      ));
	}

	public function down()
	{
		$this->removeColumn('sitemap_seo_data', 'content');
	}
}