<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlterPM137Migration extends Doctrine_Migration
{
	public function up()
	{
    $this->addColumn('p_m', 'priority', 'enum', array(
      'values' => 
             array(
              0 => 'none',
              1 => 'low',
              2 => 'mid',
              3 => 'high',
             ),
       'default' => 'none',
       'notnull' => true,
      ''
    ));
	}

	public function down()
	{
		$this->removeColumn('p_m', 'priority');
	}
}