<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlterImportLog138Migration extends Doctrine_Migration
{
	public function up()
	{
    $this->addColumn('import_log', 'errors', 'integer', array(
       'unsigned' => true,
       'length' => 4,
       'default' => 0,
       'notnull' => true,
    ));
	}

	public function down()
	{
		$this->removeColumn('import_log', 'errors');
	}
}