<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlterLot140Migration extends Doctrine_Migration
{
	public function up()
	{
    $this->addColumn('lot', 'internal_id', 'integer', array(
       'unsigned' => true,
       'length' => 5,
    ));
	}

	public function down()
	{
		$this->removeColumn('lot', 'internal_id');
	}
}