<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModifyImportErrorsLog142Migration extends Doctrine_Migration
{
  public function up()
  {
    $this->changeColumn('import_errors_log', 'internal_lot_id', 'integer', array(
      'length'  => 5,
    ));
  }

  public function down()
  {  
    $this->changeColumn('import_errors_log', 'internal_lot_id', 'integer', array(
      'length'  => 4,
    ));
  }
}