<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModifyImportRegionsLog143Migration extends Doctrine_Migration
{
  public function up()
  {
    $this->changeColumn('import_regions_log', 'lots', 'integer', array(
      'length'  => 3,
    ));
  }

  public function down()
  {  
    $this->changeColumn('import_regions_log', 'lots', 'integer', array(
      'length'  => 1,
    ));
  }
}