<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PaidImport149Migration extends Doctrine_Migration
{
	public function up()
	{
    $this->createTable('import_order', array(
      'id' => array(
        'type' => 'integer',
        'unsigned' => true,
        'primary' => true,
        'autoincrement' => true,
        'length' => 4,
      ),
      'user_id' => array(
        'type' => 'integer',
        'unsigned' => true,
        'length' => 4,
      ),
      'date_from' => array(
        'type' => 'timestamp',
        'notnull' => true,
        'length' => 25,
      ),
      'date_to' => array(
        'type' => 'timestamp',
        'notnull' => true,
        'length' => 25,
      ),
      'created_at' => array(
        'type' => 'timestamp',
        'notnull' => true,
        'length' => 25,
      ),
      'status' => array(
        'type' => 'enum',
        'values' => array(
          0 => 'inactive',
          1 => 'active',
        ),
        'notnull' => true,
        'default' => 'inactive'
      ),
      'company_name' => array(
        'type' => 'string',
        'length' => 255,
      ),
      'total' => array(
        'type' => 'integer',
        'unsigned' => true,
        'length' => 4,
      ),
      'data' => array(
        'type' => 'string',
        'length' => 2000,
      ),
    ));

    $this->createTable('import_order_options', array(
      'id' => array(
        'type' => 'integer',
        'unsigned' => true,
        'primary' => true,
        'autoincrement' => true,
        'length' => 4,
      ),
      'type' => array(
        'type' => 'enum',
        'values' => array(
          0 => 'apartament-sale',
          1 => 'apartament-rent',
          2 => 'house-sale',
          3 => 'house-rent',
          4 => 'commercial-sale',
          5 => 'commercial-rent',
          6 => 'new_building-sale'
        ),
        'notnull' => true,
      ),
      'order_id' => array(
        'type' => 'integer',
        'unsigned' => true,
        'length' => 4,
        'notnull' => true,
      ),
      'status' => array(
        'type' => 'enum',
        'values' => array(
          0 => 'inactive',
          1 => 'active',
        ),
        'notnull' => true,
        'default' => 'inactive'
      ),
    ), array(
      'unique' => array(
        0 => 'type',
        1 => 'order_id',
      ), 
    ));
   
    $this->changeColumn('lot', 'status', 'enum', array(
      'values'  => array(
        0 => 'active',
        1 => 'inactive',
        2 => 'restricted',
        3 => 'moderate',
        4 => 'not-paid',
      ),
      'default' => 'active',
    ));
    
    $this->changeColumn('user_sources_link', 'status', 'enum', array(
      'notnull'  => true,
      'values'   => array('active', 'banned', 'restored', 'not-paid'),
      'default' => 'active',
    ));
	}

	public function down()
	{
    $this->dropTable('import_order');
    $this->dropTable('import_order_options');
    $this->changeColumn('user_sources_link', 'status', 'enum', array(
      'notnull'  => true,
      'values'   => array('active', 'banned', 'restored'),
      'default' => 'active',
    ));
    $this->changeColumn('lot', 'status', 'enum', array(
      'values'  => array(
        0 => 'active',
        1 => 'inactive',
        2 => 'restricted',
        3 => 'moderate',
      ),
      'default' => 'active',
    ));
	}
}