<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlterLot151Migration extends Doctrine_Migration
{
	public function up()
	{
    $this->removeIndex('lot', 'organization_link');
    $this->changeColumn('lot', 'organization_link', 'string', array('length' => '500'));
	}

	public function down()
	{
		$this->changeColumn('lot', 'organization_link', 'string', array('length' => '100'));
    $this->addIndex('lot', 'organization_link', array(
      'fields'  =>  array('organization_link')
    ));
	}
}