<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddSpecialTargeting152Migration extends Doctrine_Migration
{
	public function up()
	{
		$this->createTable('special_targeting', array(
             'id' =>
             array(
              'type' => 'integer',
              'unsigned' => true,
              'primary' => true,
              'autoincrement' => true,
              'length' => 4,
             ),
             'name' =>
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 100,
             ),
             'text' =>
             array(
              'type' => 'string',
              'length' => NULL,
             ),
             'slug' =>
             array(
              'type' => 'string',
              'length' => 255,
             ),
             ), array(
             'indexes' =>
             array(
              'sluggable' =>
              array(
              'fields' =>
              array(
               0 => 'slug',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' =>
             array(
              0 => 'id',
             ),
             ));
	}

	public function down()
	{
		$this->dropTable('special_targeting');
	}
}