<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RenameFormToFormItem158Migration extends Doctrine_Migration_Base
{
    public function up()
    {
      $this->renameTable('form', 'form_item');
    }

    public function down()
    {
      $this->renameTable('form_item', 'form');
    }
}