<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddLandingPages159Migration extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('landing_page', array(
             'id' => 
             array(
              'type' => 'integer',
              'unsigned' => '1',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'url' => 
             array(
              'type' => 'string',
              'unique' => '1',
              'notnull' => '1',
              'length' => '255',
             ),
             'h1' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => '5000',
             ),
             'keywords' => 
             array(
              'type' => 'string',
              'length' => '1000',
             ),
             'seo_text' => 
             array(
              'type' => 'string',
              'length' => '5000',
             ),
             'params' => 
             array(
              'type' => 'array',
              'length' => '',
             ),
             'query' => 
             array(
              'type' => 'string',
              'length' => '5000',
             ),
             'region_id' => 
             array(
              'type' => 'integer',
              'unsigned' => '1',
              'notnull' => '1',
              'length' => '1',
             ),
             'type' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'apartament-sale',
              1 => 'apartament-rent',
              2 => 'house-sale',
              3 => 'house-rent',
              4 => 'commercial-sale',
              5 => 'commercial-rent',
              6 => 'new_building-sale',
              ),
              'length' => '',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        
        $this->createForeignKey('landing_page', 'landing_page_region_id_region_id', array(
             'name' => 'landing_page_region_id_region_id',
             'local' => 'region_id',
             'foreign' => 'id',
             'foreignTable' => 'region',
             'onUpdate' => '',
             'onDelete' => 'cascade',
             ));
        $this->addIndex('landing_page', 'landing_page_region_id', array(
             'fields' => 
             array(
              0 => 'region_id',
             ),
             ));
        $this->addIndex('landing_page', 'region_id', array(
             'fields' => 
             array(
              0 => 'region_id',
             ),
             ));
        $this->addIndex('landing_page', 'type', array(
             'fields' => 
             array(
              0 => 'type',
             ),
             ));
    }

    public function down()
    {
      $this->dropForeignKey('landing_page', 'landing_page_region_id_region_id');
        $this->removeIndex('landing_page', 'landing_page_region_id', array(
             'fields' => 
             array(
              0 => 'region_id',
             ),
             ));
        $this->removeIndex('landing_page', 'region_id', array(
             'fields' => 
             array(
              0 => 'region_id',
             ),
             ));
        $this->removeIndex('landing_page', 'type', array(
             'fields' => 
             array(
              0 => 'type',
             ),
             ));
      
        $this->dropTable('landing_page');
    }
}