<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddSlugFieldToLot163Migration extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('lot', 'slug', 'string', '500', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('lot', 'slug');
    }
}