<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version164 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('post', 'main_region_id', 'integer', '1', array(
             'unsigned' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('post', 'main_region_id');
    }
}