<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version165 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('post', 'post_main_region_id_region_id', array(
             'name' => 'post_main_region_id_region_id',
             'local' => 'main_region_id',
             'foreign' => 'id',
             'foreignTable' => 'region',
             ));
        $this->addIndex('post', 'post_main_region_id', array(
             'fields' => 
             array(
              0 => 'main_region_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('post', 'post_main_region_id_region_id');
        $this->removeIndex('post', 'post_main_region_id', array(
             'fields' => 
             array(
              0 => 'main_region_id',
             ),
             ));
    }
}