<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version166 extends Doctrine_Migration_Base
{
	public function up()
	{
    echo "Create Index currency_idx" . PHP_EOL;
    $this->addIndex('lot', 'currency', array(
      'fields' =>
        array(
          0 => 'currency',
        )
    ));
	}

	public function down()
	{
    $this->removeIndex('lot', 'currency');
    echo "Drop Index currency_idx" . PHP_EOL;
  }
}