<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version167 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('lot', 'hidden_description', 'string', '1500', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('lot', 'hidden_description');
    }
}