<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version169 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('regionnode', 'seotext');
        $this->addColumn('region', 'seotext', 'string', '5000', array(
             ));
    }

    public function down()
    {
        $this->addColumn('regionnode', 'seotext', 'string', '5000', array(
             ));
        $this->removeColumn('region', 'seotext');
    }
}