<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddRegionnodeGeo170Migration extends Doctrine_Migration_Base {

  public function up() {
    $this->addColumn('regionnode', 'latitude', 'double');
    $this->addColumn('regionnode', 'longitude', 'double');
  }

  public function down() {
    $this->removeColumn('regionnode', 'latitude');
    $this->removeColumn('regionnode', 'longitude');
  }

}