<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddLandingpageGeo171Migration extends Doctrine_Migration_Base {

  public function up() {
    $this->addColumn('landing_page', 'latitude', 'double');
    $this->addColumn('landing_page', 'longitude', 'double');
  }

  public function down() {
    $this->removeColumn('landing_page', 'latitude');
    $this->removeColumn('landing_page', 'longitude');
  }

}