<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChangeLotImagesFieldSize174Migration extends Doctrine_Migration_Base
{
    public function up()
    {
      $this->changeColumn('lot', 'images', 'string', '', array());
    }

    public function down()
    {
      $this->changeColumn('lot', 'images', 'string(50)', '', array());
    }
}