<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddSlugToPostAndBlogPost175Migration extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('post', 'slug', 'string', '255', array(
             'notnull' => '1',
           ));
    }

    public function down()
    {
        $this->removeColumn('post', 'slug');
    }
}