<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddCottagesMigrationVersion176 extends Doctrine_Migration_Base
{
    public function up()
    {
      $this->changeColumn('form_item', 'type', 'enum', '', array(
        'values' => 
          array(
            0 => 'apartament-sale',
            1 => 'apartament-rent',
            2 => 'house-sale',
            3 => 'house-rent',
            4 => 'commercial-sale',
            5 => 'commercial-rent',
            6 => 'new_building-sale',
            7 => 'cottage-sale',
          ),
      ));
      $this->changeColumn('import_order_options', 'type', 'enum', '', array(
        'values' => 
          array(
            0 => 'apartament-sale',
            1 => 'apartament-rent',
            2 => 'house-sale',
            3 => 'house-rent',
            4 => 'commercial-sale',
            5 => 'commercial-rent',
            6 => 'new_building-sale',
            7 => 'cottage-sale',
          ),
      ));
      $this->changeColumn('landing_page', 'type', 'enum', '', array(
        'values' => 
          array(
            0 => 'apartament-sale',
            1 => 'apartament-rent',
            2 => 'house-sale',
            3 => 'house-rent',
            4 => 'commercial-sale',
            5 => 'commercial-rent',
            6 => 'new_building-sale',
            7 => 'cottage-sale',
          ),
      ));
      $this->changeColumn('lot', 'type', 'enum', '', array(
        'values' => 
          array(
            0 => 'apartament-sale',
            1 => 'apartament-rent',
            2 => 'house-sale',
            3 => 'house-rent',
            4 => 'commercial-sale',
            5 => 'commercial-rent',
            6 => 'new_building-sale',
            7 => 'cottage-sale',
          ),
      ));
      $this->changeColumn('lot_statistic', 'type', 'enum', '', array(
        'values' => 
          array(
            0 => 'apartament-sale',
            1 => 'apartament-rent',
            2 => 'house-sale',
            3 => 'house-rent',
            4 => 'commercial-sale',
            5 => 'commercial-rent',
            6 => 'new_building-sale',
            7 => 'cottage-sale',
          ),
      ));
      $this->changeColumn('lot_view', 'lot_type', 'enum', '', array(
        'values' => 
          array(
            0 => 'apartament-sale',
            1 => 'apartament-rent',
            2 => 'house-sale',
            3 => 'house-rent',
            4 => 'commercial-sale',
            5 => 'commercial-rent',
            6 => 'new_building-sale',
            7 => 'cottage-sale',
          ),
      ));
    }

    public function down()
    {}
}