<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddCottagesEntityMigrationVersion177 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('cottage', array(
             'id' => 
             array(
              'type' => 'integer',
              'unsigned' => '1',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'lot_id' => 
             array(
              'type' => 'integer',
              'unsigned' => '1',
              'notnull' => '1',
              'length' => '4',
             ),
             'common_space' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'area_space' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'price' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'currency' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'rur',
              1 => 'eur',
              2 => 'usd',
              ),
              'length' => '',
             ),
             'decription' => 
             array(
              'type' => 'string',
              'length' => '5000',
             ),
            'type' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'cottage',
              1 => 'townhouse',
              ),
              'length' => '',
             ),
             ), array(
             'indexes' => 
             array(
              'lot_id' => 
              array(
              'fields' => 
              array(
               0 => 'lot_id',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->addIndex('cottage', 'cottage_lot_id', array(
             'fields' => 
             array(
              0 => 'lot_id',
             ),
             ));
        $this->createForeignKey('cottage', 'cottage_lot_id_lot_id', array(
             'name' => 'cottage_lot_id_lot_id',
             'local' => 'lot_id',
             'foreign' => 'id',
             'foreignTable' => 'lot',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
    }

    public function down()
    {
        $this->dropForeignKey('cottage', 'cottage_lot_id_lot_id');
        $this->removeIndex('cottage', 'cottage_lot_id', array(
             'fields' => 
             array(
              0 => 'lot_id',
             ),
             ));
        $this->dropTable('cottage');
    }
}