<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlterNbFlatFloatSpacesMigrationVersion178 extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->changeColumn('flat', 'common_space', 'float', '', array());
    $this->changeColumn('flat', 'living_space', 'float', '', array());
    $this->changeColumn('flat', 'kitchen_space', 'float', '', array());
    
    $q = Doctrine_Manager::getInstance()->getCurrentConnection();
    $q->execute("UPDATE `form_field` SET `type` = 'float' WHERE `id` IN (72,73)");
  }

  public function down()
  {
    $this->changeColumn('flat', 'common_space', 'integer', '', array());
    $this->changeColumn('flat', 'living_space', 'integer', '', array());
    $this->changeColumn('flat', 'kitchen_space', 'integer', '', array());
    
    $q = Doctrine_Manager::getInstance()->getCurrentConnection();
    $q->execute("UPDATE `form_field` SET `type` = 'integer' WHERE `id` IN (72,73)");
  }
}