<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseGeoIpRu extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('geo_ip_ru');
        $this->hasColumn('start', 'integer', 10, array('type' => 'integer', 'unsigned' => true, 'primary' => true, 'length' => '10'));
        $this->hasColumn('end', 'integer', 10, array('type' => 'integer', 'unsigned' => true, 'primary' => true, 'length' => '10'));
        $this->hasColumn('region_id', 'integer', 1, array('type' => 'integer', 'unsigned' => '1', 'length' => '1'));
        $this->hasColumn('region', 'string', 80, array('type' => 'string', 'length' => '80'));
        $this->hasColumn('city', 'string', 60, array('type' => 'string', 'length' => '60'));
    }

}